#!/usr/bin/env bash
#
# fetch-feature-s3o.sh — populate tools/feature-s3o/<entry>.s3o from the
# upstream beyond-all-reason/mapfeatures repo. One .s3o per CATALOG
# ENTRY (not per family) so the FeatureDecalRegistry can bake a
# distinct 3D thumbnail for every variant (Sprint 29b / ADR-047).
#
# Why a script (not build.rs): same as fetch-feature-decals.sh + the
# others — build.rs network access is hostile to offline builds, CI
# without network, and reproducible packaging.
#
# Why no in-repo redistribution: upstream mapfeatures has AI_POLICY.md
# but NO LICENSE file. We do not vendor models inside this repo or
# any built artifact; the user opts in by running this script
# locally. tools/feature-s3o/ is gitignored.
#
# Idempotent: per-entry files are skipped if already installed. Re-runs
# after `git pull` upstream pick up the freshest model only when
# --refresh is passed.

set -euo pipefail

# ---- paths -----------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DEST_ROOT="$REPO_ROOT/tools/feature-s3o"

UPSTREAM_DIR="${BARME_MAPFEATURES_DIR:-$HOME/code/Beyond-All-Reason/mapfeatures}"
UPSTREAM_URL="https://github.com/beyond-all-reason/mapfeatures.git"
# Pin captured during the Sprint 29 audit (2026-05-21). Sprint 29b
# uses the same pin since the featureDef Lua walk that produced this
# list was against the same upstream commit. If upstream moves, the
# script logs a warning but still uses whatever the clone resolves.
PINNED_COMMIT="3b791639210dcc4f89875fce712bde8f460d38e1"

# ---- catalog of entry → upstream s3o path ----------------------------------
# Each ENTRY is "<catalog_entry_name>:<path_under_mapfeatures/objects3d/>".
# Mirrors assets/mapfeatures_catalog.json — per-entry `s3o` override when
# set, else family `s3o_pattern` with {name} substituted. Generated by
# walking mapfeatures/features/*.lua (commit 3b79163).
#
# Families NOT listed here (rocks30, tombstone, xmascomwreck, geovent):
# upstream-absent. Their entries stay on Phase A's category-glyph
# fallback. Phase C work — when a BAR-clone fetch script lands, those
# 8 entries can move here.
ENTRIES=(
    # ad0_aleppo2 (4)
    "ad0_aleppo2_sparse_med_m:ad0_aleppo2_sparse_med_m.s3o"
    "ad0_aleppo2_dense_med_l:ad0_aleppo2_dense_med_l.s3o"
    "ad0_aleppo2_double_dark_xl:ad0_aleppo2_double_dark_xl.s3o"
    "ad0_aleppo2_dense_dead_l:ad0_aleppo2_dense_dead_l.s3o"
    # ad0_banyan (6) — subfolder
    "ad0_banyan_1:ad0_banyan/ad0_banyan_1.s3o"
    "ad0_banyan_2:ad0_banyan/ad0_banyan_2.s3o"
    "ad0_banyan_3:ad0_banyan/ad0_banyan_3.s3o"
    "ad0_banyan_4:ad0_banyan/ad0_banyan_4.s3o"
    "ad0_banyan_5:ad0_banyan/ad0_banyan_5.s3o"
    "ad0_banyan_6:ad0_banyan/ad0_banyan_6.s3o"
    # ad0_cedar_atlas (4) — subfolder
    "cedar_atlas_1__cedar_atlas_1:ad0_cedar_atlas/cedar_atlas_1__cedar_atlas_1.s3o"
    "cedar_atlas_2__cedar_atlas_2:ad0_cedar_atlas/cedar_atlas_2__cedar_atlas_2.s3o"
    "cedar_atlas_3__cedar_atlas_dead:ad0_cedar_atlas/cedar_atlas_3__cedar_atlas_dead.s3o"
    "cedar_atlas_young_2__cedar_atlas_1:ad0_cedar_atlas/cedar_atlas_young_2__cedar_atlas_1.s3o"
    # ad0_fir (4) — subfolder
    "fir_tree_small_1__tree_fir_tall_1:ad0_fir/fir_tree_small_1__tree_fir_tall_1.s3o"
    "fir_tree_small_2__tree_fir_tall_3:ad0_fir/fir_tree_small_2__tree_fir_tall_3.s3o"
    "fir_tree_tall_1__tree_fir_tall_3:ad0_fir/fir_tree_tall_1__tree_fir_tall_3.s3o"
    "fir_tree_tall_3__tree_fir_tall_5:ad0_fir/fir_tree_tall_3__tree_fir_tall_5.s3o"
    # ad0_senegal (6)
    "ad0_senegal_1:ad0_senegal_1.s3o"
    "ad0_senegal_2:ad0_senegal_2.s3o"
    "ad0_senegal_3:ad0_senegal_3.s3o"
    "ad0_senegal_1_large:ad0_senegal_1_large.s3o"
    "ad0_senegal_2_large:ad0_senegal_2_large.s3o"
    "ad0_senegal_3_large:ad0_senegal_3_large.s3o"
    # agorm_rock (5) — per-entry override: rockN.s3o, not agorm_rockN.s3o
    "agorm_rock1:rock1.s3o"
    "agorm_rock2:rock2.s3o"
    "agorm_rock3:rock3.s3o"
    "agorm_rock4:rock4.s3o"
    "agorm_rock5:rock5.s3o"
    # allpinesb_ad0 (6)
    "allpinesb_ad0_green_b_m:allpinesb_ad0_green_b_m.s3o"
    "allpinesb_ad0_green_c_l:allpinesb_ad0_green_c_l.s3o"
    "allpinesb_ad0_green_a_xl:allpinesb_ad0_green_a_xl.s3o"
    "allpinesb_ad0_brown_b_l:allpinesb_ad0_brown_b_l.s3o"
    "allpinesb_ad0_snow_b_m:allpinesb_ad0_snow_b_m.s3o"
    "allpinesb_ad0_snowgreen_c_l:allpinesb_ad0_snowgreen_c_l.s3o"
    # anemone (6)
    "anemone1:anemone1.s3o"
    "anemone2:anemone2.s3o"
    "anemone3:anemone3.s3o"
    "anemone4:anemone4.s3o"
    "anemone5:anemone5.s3o"
    "anemone6:anemone6.s3o"
    # birchtree (6)
    "euro_birch_tree_01_1:euro_birch_tree_01_1.s3o"
    "euro_birch_tree_02_1:euro_birch_tree_02_1.s3o"
    "euro_birch_tree_03_1:euro_birch_tree_03_1.s3o"
    "euro_birch_tree_04_1:euro_birch_tree_04_1.s3o"
    "euro_birch_tree_01_4:euro_birch_tree_01_4.s3o"
    "euro_birch_tree_03_4:euro_birch_tree_03_4.s3o"
    # cycas (4) — per-entry override: fernN.s3o, not cycasN.s3o
    "cycas1:fern1.s3o"
    "cycas2:fern2.s3o"
    "cycas4:fern4.s3o"
    "cycas6:fern6.s3o"
    # kapok (4)
    "kapok1:kapok1.s3o"
    "kapok2:kapok2.s3o"
    "kapok3:kapok3.s3o"
    "kapok4:kapok4.s3o"
    # mushroom_orange (4)
    "mushroom01:mushroom01.s3o"
    "mushroom03:mushroom03.s3o"
    "mushroom05:mushroom05.s3o"
    "mushroom07:mushroom07.s3o"
    # mushroom_purple (4)
    "mushroom11:mushroom11.s3o"
    "mushroom13:mushroom13.s3o"
    "mushroom15:mushroom15.s3o"
    "mushroom17:mushroom17.s3o"
    # mushroom_tan (4)
    "mushroom21:mushroom21.s3o"
    "mushroom23:mushroom23.s3o"
    "mushroom25:mushroom25.s3o"
    "mushroom27:mushroom27.s3o"
    # pdrock (8) — subfolder
    "pdrock1:pdrock/pdrock1.s3o"
    "pdrock2:pdrock/pdrock2.s3o"
    "pdrock3:pdrock/pdrock3.s3o"
    "pdrock4:pdrock/pdrock4.s3o"
    "pdrock5:pdrock/pdrock5.s3o"
    "pdrock6:pdrock/pdrock6.s3o"
    "pdrock7:pdrock/pdrock7.s3o"
    "pdrock8:pdrock/pdrock8.s3o"
    # pedro (6)
    "pedro1:pedro1.s3o"
    "pedro2:pedro2.s3o"
    "pedro3:pedro3.s3o"
    "pedro4:pedro4.s3o"
    "pedro5:pedro5.s3o"
    "pedro6:pedro6.s3o"
    # peyote (4)
    "peyote1:peyote1.s3o"
    "peyote2:peyote2.s3o"
    "peyote3:peyote3.s3o"
    "peyote4:peyote4.s3o"
)

# ---- args ------------------------------------------------------------------
MODE='install'
while [ $# -gt 0 ]; do
    case "$1" in
        --check)
            MODE='check'
            ;;
        --refresh)
            MODE='refresh'
            ;;
        --help|-h)
            cat <<EOF
Usage: $0 [--check|--refresh]

Without flags:
  Idempotently copy upstream mapfeatures S3O files into
  $DEST_ROOT/<entry>.s3o. Clones upstream into $UPSTREAM_DIR if
  not present. Skips entries whose destination file already exists.

--check:
  Verify the upstream clone exists, every advertised S3O is
  reachable inside it, and every installed file is non-empty. Does
  not download or copy. Exit non-zero on any miss.

--refresh:
  Force-overwrite every destination file from upstream (does NOT
  re-clone, only the destination is rewritten — use 'git -C
  $UPSTREAM_DIR pull' yourself if you want a fresh upstream).

env BARME_MAPFEATURES_DIR=<path>
  Override the upstream clone path. Default
  $HOME/code/Beyond-All-Reason/mapfeatures.

License note: upstream has no LICENSE file. tools/feature-s3o/ is
gitignored — these models never enter the BAR Map Editor repo or
any release artifact. The user opts in by running this script.

EOF
            exit 0
            ;;
        *)
            printf 'fetch-feature-s3o: unknown flag: %s (try --help)\n' "$1" >&2
            exit 2
            ;;
    esac
    shift
done

# ---- ensure upstream clone -------------------------------------------------
ensure_upstream() {
    if [ -d "$UPSTREAM_DIR/.git" ]; then
        return 0
    fi
    if [ "$MODE" = 'check' ]; then
        printf 'fetch-feature-s3o: upstream clone missing at %s\n' \
            "$UPSTREAM_DIR" >&2
        printf '  run "%s" without --check to clone it.\n' "$0" >&2
        exit 1
    fi
    printf 'fetch-feature-s3o: cloning %s -> %s (shallow)\n' \
        "$UPSTREAM_URL" "$UPSTREAM_DIR"
    mkdir -p "$(dirname "$UPSTREAM_DIR")"
    git clone --depth 1 "$UPSTREAM_URL" "$UPSTREAM_DIR"
}

warn_on_pin_drift() {
    local head
    head="$(git -C "$UPSTREAM_DIR" rev-parse HEAD 2>/dev/null || echo unknown)"
    if [ "$head" != "$PINNED_COMMIT" ]; then
        printf '  note: upstream HEAD is %s (pin was %s); mapping may have drifted.\n' \
            "${head:0:8}" "${PINNED_COMMIT:0:8}"
    fi
}

ensure_upstream
warn_on_pin_drift

# ---- check mode ------------------------------------------------------------
if [ "$MODE" = 'check' ]; then
    fail=0
    for entry in "${ENTRIES[@]}"; do
        name="${entry%%:*}"
        path="${entry#*:}"
        src="$UPSTREAM_DIR/objects3d/$path"
        dst="$DEST_ROOT/$name.s3o"
        if [ ! -f "$src" ]; then
            printf '  [%s] UPSTREAM MISSING: %s\n' "$name" "$src" >&2
            fail=1
            continue
        fi
        if [ -f "$dst" ] && [ ! -s "$dst" ]; then
            printf '  [%s] LOCAL EMPTY: %s (re-run without --check)\n' \
                "$name" "$dst" >&2
            fail=1
            continue
        fi
    done
    if [ "$fail" -ne 0 ]; then
        printf 'fetch-feature-s3o: --check failed\n' >&2
        exit 1
    fi
    printf 'fetch-feature-s3o: --check ok (%d entries advertised)\n' "${#ENTRIES[@]}"
    exit 0
fi

# ---- install / refresh -----------------------------------------------------
mkdir -p "$DEST_ROOT"

installed=0
skipped=0
missing=0

for entry in "${ENTRIES[@]}"; do
    name="${entry%%:*}"
    path="${entry#*:}"
    src="$UPSTREAM_DIR/objects3d/$path"
    dst="$DEST_ROOT/$name.s3o"

    if [ ! -f "$src" ]; then
        printf '  [%s] UPSTREAM MISSING %s\n' "$name" "$src" >&2
        missing=$((missing + 1))
        continue
    fi

    if [ -f "$dst" ] && [ "$MODE" != 'refresh' ]; then
        skipped=$((skipped + 1))
        continue
    fi

    cp "$src" "$dst"
    installed=$((installed + 1))
done

printf 'fetch-feature-s3o: %d installed, %d skipped, %d missing (of %d advertised).\n' \
    "$installed" "$skipped" "$missing" "${#ENTRIES[@]}"

if [ "$missing" -gt 0 ]; then
    printf '  %d entries lack an upstream .s3o — runtime falls back\n' \
        "$missing" >&2
    printf '  to the Phase A decal sprite for those.\n' >&2
fi
