//! Springboard feature-placer integration (`LuaGaia/Gadgets/FP_featureplacer.lua`
//! + `mapconfig/featureplacer/{config,set}.lua`).
//!
//! ## Why this isn't a single Lua file
//!
//! Pre-Sprint-11 the editor emitted a flat
//! `mapconfig/featureplacer/features.lua` returning a feature array.
//! **BAR has no gadget that reads that path** — verified against the
//! `Beyond-All-Reason` HEAD by direct grep (no consumer in
//! `luarules/`, `luaui/`, or `common/`). Features in BAR-compatible
//! maps reach the engine via the Springboard featureplacer pattern:
//!
//! 1. `LuaGaia/Gadgets/FP_featureplacer.lua` — the PD-licensed
//!    "FeaturePlacer" gadget by Gnome / Smoth (August 2008). Bundled
//!    into the `.sd7` as map-side cargo; BAR auto-loads
//!    `LuaGaia/Gadgets/*.lua` on map start.
//! 2. `mapconfig/featureplacer/config.lua` — one-liner redirect
//!    returning `VFS.Include("mapconfig/featureplacer/set.lua")`.
//! 3. `mapconfig/featureplacer/set.lua` — the actual data,
//!    `return { objectlist = {...}, unitlist = {...},
//!    buildinglist = {...} }`. Features get added to `objectlist`;
//!    `unitlist` and `buildinglist` are reserved for map-side stock
//!    units (e.g. a campaign mission's pre-placed gaia commander).
//!
//! See `/tmp/sd7-inspect/LuaGaia/Gadgets/FP_featureplacer.lua` (extracted
//! from `gecko_isle_remake_v1.2.1.sd7`) for the canonical gadget body;
//! we vendor a verbatim copy under `assets/FP_featureplacer.lua` and
//! `lib.rs::build_sd7` stages it on every build.
//!
//! ## Schema in `set.lua`
//!
//! ```lua
//! local setcfg = {
//!   unitlist = {},
//!   buildinglist = {},
//!   objectlist = {
//!     { name = "geovent", x = 4096, z = 4096, rot = 0 },
//!     { name = "agorm_talltree6", x = 224, z = 3616, rot = -23991 },
//!   },
//! }
//! return setcfg
//! ```
//!
//! Rotation is an **unquoted integer** (Spring heading units,
//! `-32768..32767`). The PyMapConv `-k` text-file format uses the
//! quoted-string form per FINDINGS §6 but that's a different
//! codepath; **for the Lua-gadget path the value must be a number**
//! because the gadget calls `Spring.CreateFeature(..., fDef.rot)`
//! which expects a numeric rotation.
//!
//! ## Y-coordinate behaviour
//!
//! `y` is intentionally absent. The gadget calls
//! `Spring.GetGroundHeight(fDef.x, fDef.z) + 5` at spawn time so
//! features ride the live terrain rather than baking a stale y from
//! editor-time. Sculpting the heightmap after authoring vents does
//! not break the placement — the engine re-samples on every load.
//!
//! ## C5 → C6 evolution
//!
//! Sprint 11 / C5 ships geo vents only. Sprint 12 / C6 lands general
//! feature placement (trees / rocks / wreckage) on top of the same
//! seam: the public `feature_entry_int` helper builds one Lua entry
//! that C6 will reuse.

use barme_core::{GeoVent, Project};

use crate::lua_ast::{LuaKey, LuaValue, serialize};

/// PD-licensed Springboard feature-placer gadget, vendored verbatim
/// from `gecko_isle_remake_v1.2.1.sd7` (which itself sourced it from
/// the 2008 release by Gnome / Smoth). Bundled into every `.sd7` at
/// `LuaGaia/Gadgets/FP_featureplacer.lua` so BAR auto-loads it on
/// map start.
pub const FP_GADGET_SOURCE: &str = include_str!("../assets/FP_featureplacer.lua");

/// Canonical name of BAR's stock geothermal-vent FeatureDef. The
/// `api_resource_spot_finder` upget looks for
/// `FeatureDef.geoThermal = true`, which this name carries; verified
/// against BAR's `sounds/atmos-geovents/` ambience binding + FINDINGS
/// §5. Map-bundled custom geos are Stage 2 (own ADR).
pub const GEOVENT_NAME: &str = "geovent";

/// Render `mapconfig/featureplacer/config.lua` — a one-liner that
/// re-exports `set.lua` so the Springboard gadget's
/// `VFS.Include("mapconfig/featureplacer/config.lua")` call ends up
/// reading our data.
pub fn render_config() -> String {
    "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
     return VFS.Include(\"mapconfig/featureplacer/set.lua\")\n"
        .to_string()
}

/// Render `mapconfig/featureplacer/set.lua` — the actual data the
/// FP_featureplacer gadget consumes: a single table-valued local
/// with `objectlist` / `unitlist` / `buildinglist` keys, returned at
/// the end. C5 populates `objectlist` from `Project.geo_vents`;
/// `unitlist` and `buildinglist` are empty until a map-side-units
/// feature lands (out of scope for Stage 1).
pub fn render_set(project: &Project) -> String {
    let objectlist = LuaValue::Seq(object_entries(project));
    let unitlist = LuaValue::Seq(Vec::new());
    let buildinglist = LuaValue::Seq(Vec::new());
    // We render the local cfg block by hand rather than wrapping it
    // in our LuaValue::Table — preserves the
    // `local setcfg = { ... }; return setcfg` shape that matches
    // existing BAR maps verbatim, so a future map authored in our
    // editor diffs cleanly against a hand-authored one.
    let entries = vec![
        (LuaKey::str("buildinglist"), buildinglist),
        (LuaKey::str("objectlist"), objectlist),
        (LuaKey::str("unitlist"), unitlist),
    ];
    let body = serialize(&LuaValue::Table(entries));
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         local setcfg = {body}\n\
         return setcfg\n"
    )
}

/// Build one entry for the `set.lua` `objectlist`. Rotation is a
/// numeric Lua integer (NOT the quoted-string form PyMapConv's `-k`
/// flag uses) because the gadget calls
/// `Spring.CreateFeature(..., fDef.rot)` which expects a number.
pub(crate) fn feature_entry_int(name: &str, x: i32, z: i32, rot_heading: i16) -> LuaValue {
    LuaValue::Table(vec![
        (LuaKey::str("name"), LuaValue::str(name)),
        (LuaKey::str("rot"), LuaValue::Int(rot_heading as i64)),
        (LuaKey::str("x"), LuaValue::Int(x as i64)),
        (LuaKey::str("z"), LuaValue::Int(z as i64)),
    ])
}

/// Walk `Project.geo_vents` and emit one feature entry per vent in
/// `(z, x)`-sorted order. C6 will append generic features after
/// the geo-vent block (sorted by `(name, z, x)`).
fn object_entries(project: &Project) -> Vec<LuaValue> {
    let mut sorted: Vec<GeoVent> = project.geo_vents.clone();
    sorted.sort_by_key(|v| (v.z_elmo, v.x_elmo));
    sorted
        .into_iter()
        .map(|v| feature_entry_int(GEOVENT_NAME, v.x_elmo, v.z_elmo, 0))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fp_gadget_is_bundled_with_expected_marker() {
        // `include_str!` would fail to compile if the asset's path
        // wasn't right; this test is a runtime sanity check that the
        // gadget body is what we expect (a contributor moving the
        // asset would catch the failure here).
        assert!(
            FP_GADGET_SOURCE.contains("FP_featureplacer")
                || FP_GADGET_SOURCE.contains("feature placer"),
            "FP_featureplacer.lua asset doesn't look like the Springboard gadget"
        );
        assert!(FP_GADGET_SOURCE.contains("VFS.Include"));
        assert!(FP_GADGET_SOURCE.contains("mapconfig/featureplacer/config.lua"));
        assert!(FP_GADGET_SOURCE.contains("CreateFeature"));
    }

    #[test]
    fn config_redirects_to_set() {
        let s = render_config();
        assert!(s.contains("return VFS.Include"));
        assert!(s.contains("mapconfig/featureplacer/set.lua"));
    }

    #[test]
    fn empty_project_emits_empty_objectlist() {
        let p = Project::new("blank", 4);
        let s = render_set(&p);
        assert!(s.contains("local setcfg ="));
        assert!(s.contains("return setcfg"));
        assert!(s.contains("buildinglist = {}"));
        assert!(s.contains("objectlist = {}"));
        assert!(s.contains("unitlist = {}"));
    }

    /// C5: two geo vents → two `name = "geovent"` entries in
    /// `objectlist`. PITFALL §14 / FINDINGS §5–§6 path verified
    /// against the BAR source.
    #[test]
    fn geo_vents_emit_geovent_objects() {
        let mut p = Project::new("vents", 8);
        p.geo_vents.push(GeoVent::new(2048, 4096));
        p.geo_vents.push(GeoVent::new(2048, 8192));
        let s = render_set(&p);
        let count = s.matches(r#"name = "geovent""#).count();
        assert_eq!(count, 2, "expected 2 geovent entries; got:\n{s}");
        assert!(s.contains("z = 4096"), "got:\n{s}");
        assert!(s.contains("z = 8192"), "got:\n{s}");
        assert!(s.contains("x = 2048"), "got:\n{s}");
    }

    /// Rotation is an UNQUOTED integer in `set.lua` (the gadget
    /// passes it straight to `Spring.CreateFeature(..., fDef.rot)`
    /// which expects a number). Confirmed against a real map
    /// (`gecko_isle_remake_v1.2.1.sd7`'s set.lua uses `rot = -23991`,
    /// not `rot = "-23991"`).
    #[test]
    fn rotation_emits_as_unquoted_integer() {
        let mut p = Project::new("rotint", 8);
        p.geo_vents.push(GeoVent::new(100, 200));
        let s = render_set(&p);
        assert!(
            s.contains("rot = 0,") || s.contains("rot = 0\n"),
            "rot must be an UNQUOTED integer for the Lua gadget path; got:\n{s}"
        );
        assert!(
            !s.contains(r#"rot = "0""#),
            "rot must NOT be a string in set.lua (that's PyMapConv's -k format); got:\n{s}"
        );
    }

    /// Stable diff order: sources are sorted by `(z, x)` even when
    /// authored out-of-order.
    #[test]
    fn geo_vents_emit_sorted_by_z_then_x() {
        let mut p = Project::new("sorted", 8);
        p.geo_vents.push(GeoVent::new(500, 800));
        p.geo_vents.push(GeoVent::new(100, 200));
        p.geo_vents.push(GeoVent::new(900, 200));
        let s = render_set(&p);
        let z200 = s.find("z = 200").expect("z=200 present");
        let z800 = s.find("z = 800").expect("z=800 present");
        assert!(z200 < z800, "smaller-z entries first; got:\n{s}");
    }

    /// Repeat render = byte-identical. Determinism gate for the SD7
    /// archive hash.
    #[test]
    fn render_set_is_deterministic() {
        let mut p = Project::new("det", 4);
        p.geo_vents.push(GeoVent::new(100, 100));
        p.geo_vents.push(GeoVent::new(200, 200));
        let a = render_set(&p);
        let b = render_set(&p);
        assert_eq!(a, b);
    }

    #[test]
    fn render_config_is_deterministic() {
        assert_eq!(render_config(), render_config());
    }

    #[test]
    fn geovent_name_constant_matches_bar_featuredef() {
        assert_eq!(GEOVENT_NAME, "geovent");
    }
}
