//! `mapconfig/featureplacer/features.lua` emitter (ADR-029).
//!
//! Path is at the **archive root** under `mapconfig/featureplacer/` —
//! NOT inside `LuaGaia/` (PITFALL — easy to confuse with the engine's
//! `FeatureDef` lookup path). Consumed by BAR's feature-placer gadget
//! and Springboard's exporter (see research §5).
//!
//! ## Shape (per research)
//!
//! ```lua
//! return {
//!   { name = "geovent",                x = 2048, z = 4096, rot = "0" },
//!   { name = "allpinesb_ad0_greena_m", x = 2100, z = 2200, rot = "16384" },
//! }
//! ```
//!
//! - `name`: FeatureDef name in the BAR mod (or a bundled
//!   `features/`-relative entry for map-custom features).
//! - `x`, `z`: elmos, integer. `y` is intentionally absent — the
//!   engine samples ground height at spawn so features float
//!   correctly under water-level changes.
//! - `rot`: **string-typed** integer in Spring heading units
//!   (`"0"` … `"65535"` representing 0–360°). The legacy string form is
//!   what the parser expects; Gemini's report incorrectly typed this
//!   as a float — adopt Claude's finding (PITFALL §6).
//!
//! ## C5 (Sprint 11): geo vents land here
//!
//! `Project.geo_vents` emits as `name = "geovent"` features —
//! PITFALL §14 / FINDINGS §5–§6: BAR's
//! `api_resource_spot_finder.GetSpotsGeo()` scans
//! `Spring.GetAllFeatures()` for `FeatureDef.geoThermal = true`
//! (the stock `geovent` carries that flag), so the steam-plume
//! visual + the GG["resource_spot_finder"].geoSpotsList registration
//! both come from a single feature placement. The legacy `geos = {}`
//! array in `map_metal_layout.lua` is Zero-K convention and does
//! NOT apply to BAR — `metal_layout.rs` therefore emits only
//! `spots`.
//!
//! C6 (Sprint 12) will land general feature placement on top of
//! the same `feature_entry` helper; the order they end up in the
//! emitted list is (geo vents) first, sorted by (z, x), then
//! whatever C6 ships, sorted by (name, z, x) for determinism.

use barme_core::{GeoVent, Project};

use crate::lua_ast::{LuaKey, LuaValue, serialize, sort_table_by_key};

/// Canonical name of BAR's stock geothermal-vent FeatureDef. The
/// `api_resource_spot_finder` upget looks for
/// `FeatureDef.geoThermal = true`, which this name carries; verified
/// against BAR's `sounds/atmos-geovents/` ambience binding + FINDINGS
/// §5. Map-bundled custom geos are Stage 2 (own ADR).
pub const GEOVENT_NAME: &str = "geovent";

/// Render the canonical `return { … }` feature list. Empty array when
/// no features are authored.
pub fn render(project: &Project) -> String {
    let items = feature_instances(project);
    let body = serialize(&LuaValue::Seq(items));
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         return {body}\n"
    )
}

/// Build one feature entry as a Lua table. Kept public-in-module so
/// C5 (geo vents) and C6 (general feature placement) can reuse it
/// when they wire up their writes.
pub(crate) fn feature_entry(name: &str, x: i32, z: i32, rot_heading: u16) -> LuaValue {
    let mut t = vec![
        (LuaKey::str("name"), LuaValue::str(name)),
        (LuaKey::str("x"), LuaValue::Int(x as i64)),
        (LuaKey::str("z"), LuaValue::Int(z as i64)),
        // rot is STRING-typed per BAR convention — Claude's source
        // audit (FINDINGS §6) confirms the parser expects the quoted
        // form. Test-pinned by `feature_entry_carries_*_rot_as_string`.
        (LuaKey::str("rot"), LuaValue::str(rot_heading.to_string())),
    ];
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

/// Build one geovent feature entry from a [`GeoVent`]. Rotation is
/// always `"0"` (Spring heading units) — the stock geovent FeatureDef
/// is rotationally symmetric, so the heading doesn't matter visually
/// and zero is the BAR-mapper convention.
fn geovent_entry(v: &GeoVent) -> LuaValue {
    feature_entry(GEOVENT_NAME, v.x_elmo, v.z_elmo, 0)
}

/// Walk the project's feature list and emit one [`LuaValue::Table`]
/// per instance. C5 ships the geo-vent path; C6 will append general
/// features after them.
fn feature_instances(project: &Project) -> Vec<LuaValue> {
    let mut out: Vec<LuaValue> = Vec::with_capacity(project.geo_vents.len());
    // Sort sources by (z, x) for stable diffs. We must not sort the
    // canonical `project.geo_vents` — App-side identity is index-
    // based — so we clone into a local vec before sorting.
    let mut sorted: Vec<GeoVent> = project.geo_vents.clone();
    sorted.sort_by_key(|v| (v.z_elmo, v.x_elmo));
    for v in &sorted {
        out.push(geovent_entry(v));
    }
    // C6 hook-point: append `project.features` here, sorted by
    // (name, z, x) for stable diffs.
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_features_emit_empty_seq() {
        let p = Project::new("blank", 4);
        let s = render(&p);
        assert!(s.contains("return {}"), "got:\n{s}");
        assert!(s.starts_with("-- Auto-generated"), "header missing");
    }

    #[test]
    fn feature_entry_carries_name_x_z_rot_as_string() {
        let v = feature_entry("geovent", 2048, 4096, 0);
        let s = serialize(&v);
        assert!(s.contains(r#"name = "geovent""#), "got:\n{s}");
        assert!(s.contains("x = 2048"), "got:\n{s}");
        assert!(s.contains("z = 4096"), "got:\n{s}");
        // rot must be STRING-typed per BAR convention.
        assert!(s.contains(r#"rot = "0""#), "rot must be string; got:\n{s}");
    }

    #[test]
    fn feature_entry_rotation_renders_as_quoted_heading() {
        // 16384 heading units = 90°. BAR convention: emit as the
        // string "16384" so the parser doesn't reject it as a number.
        let v = feature_entry("rock_a", 2000, 3000, 16384);
        let s = serialize(&v);
        assert!(s.contains(r#"rot = "16384""#), "got:\n{s}");
    }

    #[test]
    fn determinism_repeated_render_byte_identical() {
        let p = Project::new("det", 4);
        let a = render(&p);
        let b = render(&p);
        assert_eq!(a, b);
    }

    /// C5: a project with two geo vents emits two `name = "geovent"`
    /// entries. Field shape verified against FINDINGS §5–§6 +
    /// PITFALL §14 (no `geos` array — features only).
    #[test]
    fn geo_vents_emit_geovent_features() {
        let mut p = Project::new("vents", 8);
        p.geo_vents.push(GeoVent::new(2048, 4096));
        p.geo_vents.push(GeoVent::new(2048, 8192));
        let s = render(&p);
        // Two entries.
        let count = s.matches(r#"name = "geovent""#).count();
        assert_eq!(count, 2, "expected 2 geovent entries; got:\n{s}");
        // Both coords surface.
        assert!(s.contains("z = 4096"), "got:\n{s}");
        assert!(s.contains("z = 8192"), "got:\n{s}");
        // X coordinate is shared across both.
        assert!(s.contains("x = 2048"), "got:\n{s}");
    }

    /// PITFALL §6 / FINDINGS §6: `rot` must be a STRING-quoted
    /// Spring heading integer. Default geo-vent rotation is `"0"`.
    #[test]
    fn geo_rotation_default_zero_string() {
        let mut p = Project::new("rotstr", 8);
        p.geo_vents.push(GeoVent::new(100, 200));
        let s = render(&p);
        assert!(
            s.contains(r#"rot = "0""#),
            "rot must be STRING-quoted; got:\n{s}"
        );
        // Defensive: make sure we didn't slip out the unquoted form
        // (which would silently work in the engine but break BAR's
        // mapper conventions + the C8 lint).
        assert!(
            !s.contains("rot = 0,") && !s.contains("rot = 0\n"),
            "no unquoted `rot = 0` allowed; got:\n{s}"
        );
    }

    /// Sources are sorted by (z, x) for stable diffs even when the
    /// user authored them in another order.
    #[test]
    fn geo_vents_emit_sorted_by_z_then_x() {
        let mut p = Project::new("sorted", 8);
        // Insertion order intentionally not (z, x)-sorted.
        p.geo_vents.push(GeoVent::new(500, 800));
        p.geo_vents.push(GeoVent::new(100, 200));
        p.geo_vents.push(GeoVent::new(900, 200));
        let s = render(&p);
        // (200, 100) → (200, 900) → (800, 500): rendered z entries
        // must appear in that order.
        let z200_a = s.find("z = 200").expect("z=200 present");
        let z800 = s.find("z = 800").expect("z=800 present");
        assert!(
            z200_a < z800,
            "smaller-z entries should sort before larger-z; got:\n{s}"
        );
    }

    /// An empty `geo_vents` vec yields the existing C2-shape empty
    /// table (no surprise regressions for projects without any
    /// vents).
    #[test]
    fn empty_geo_vents_emit_empty_seq() {
        let p = Project::new("blank-vents", 4);
        let s = render(&p);
        assert!(s.contains("return {}"), "got:\n{s}");
    }

    /// Verify the geovent name constant: typo here would render the
    /// vents as non-existent features and BAR would silently skip
    /// them with `[GetFeatureDef] could not find FeatureDef`.
    #[test]
    fn geovent_name_constant_matches_bar_featuredef() {
        assert_eq!(GEOVENT_NAME, "geovent");
    }
}
