//! Springboard feature-placer integration (`LuaGaia/Gadgets/FP_featureplacer.lua`
//! + `mapconfig/featureplacer/{config,set}.lua`).
//!
//! ## Why this isn't a single Lua file
//!
//! Pre-Sprint-11 the editor emitted a flat
//! `mapconfig/featureplacer/features.lua` returning a feature array.
//! **BAR has no gadget that reads that path** — verified against the
//! `Beyond-All-Reason` HEAD by direct grep (no consumer in
//! `luarules/`, `luaui/`, or `common/`). Features in BAR-compatible
//! maps reach the engine via the Springboard featureplacer pattern:
//!
//! 1. `LuaGaia/Gadgets/FP_featureplacer.lua` — the PD-licensed
//!    "FeaturePlacer" gadget by Gnome / Smoth (August 2008). Bundled
//!    into the `.sd7` as map-side cargo; BAR auto-loads
//!    `LuaGaia/Gadgets/*.lua` on map start.
//! 2. `mapconfig/featureplacer/config.lua` — one-liner redirect
//!    returning `VFS.Include("mapconfig/featureplacer/set.lua")`.
//! 3. `mapconfig/featureplacer/set.lua` — the actual data,
//!    `return { objectlist = {...}, unitlist = {...},
//!    buildinglist = {...} }`. Features get added to `objectlist`;
//!    `unitlist` and `buildinglist` are reserved for map-side stock
//!    units (e.g. a campaign mission's pre-placed gaia commander).
//!
//! See `/tmp/sd7-inspect/LuaGaia/Gadgets/FP_featureplacer.lua` (extracted
//! from `gecko_isle_remake_v1.2.1.sd7`) for the canonical gadget body;
//! we vendor a verbatim copy under `assets/FP_featureplacer.lua` and
//! `lib.rs::build_sd7` stages it on every build.
//!
//! ## Schema in `set.lua`
//!
//! ```lua
//! local setcfg = {
//!   unitlist = {},
//!   buildinglist = {},
//!   objectlist = {
//!     { name = "geovent", x = 4096, z = 4096, rot = 0 },
//!     { name = "agorm_talltree6", x = 224, z = 3616, rot = -23991 },
//!   },
//! }
//! return setcfg
//! ```
//!
//! Rotation is an **unquoted integer** (Spring heading units,
//! `-32768..32767`). The PyMapConv `-k` text-file format uses the
//! quoted-string form per FINDINGS §6 but that's a different
//! codepath; **for the Lua-gadget path the value must be a number**
//! because the gadget calls `Spring.CreateFeature(..., fDef.rot)`
//! which expects a numeric rotation.
//!
//! ## Y-coordinate behaviour
//!
//! `y` is intentionally absent. The gadget calls
//! `Spring.GetGroundHeight(fDef.x, fDef.z) + 5` at spawn time so
//! features ride the live terrain rather than baking a stale y from
//! editor-time. Sculpting the heightmap after authoring vents does
//! not break the placement — the engine re-samples on every load.
//!
//! ## C5 → C6 evolution
//!
//! Sprint 11 / C5 ships geo vents only. Sprint 12 / C6 lands general
//! feature placement (trees / rocks / wreckage) on top of the same
//! seam: the public `feature_entry_int` helper builds one Lua entry
//! that C6 will reuse.

use barme_core::{FeatureInstance, GeoVent, Project};
use tracing::warn;

use crate::lua_ast::{LuaKey, LuaValue, serialize};

/// PD-licensed Springboard feature-placer gadget, vendored verbatim
/// from `gecko_isle_remake_v1.2.1.sd7` (which itself sourced it from
/// the 2008 release by Gnome / Smoth). Bundled into every `.sd7` at
/// `LuaGaia/Gadgets/FP_featureplacer.lua` so BAR auto-loads it on
/// map start.
pub const FP_GADGET_SOURCE: &str = include_str!("../assets/FP_featureplacer.lua");

/// LuaGaia bootstrap that triggers the engine-side gadget handler.
/// Without this file at `LuaGaia/main.lua` in the SD7, Recoil never
/// scans `LuaGaia/Gadgets/` and our `FP_featureplacer.lua` is dead
/// code. Verified by extracting `springcontent.sdz` (recoil
/// 2026.06.04) — the engine provides `LuaGadgets/gadgets.lua` but
/// NOT a fallback `LuaGaia/main.lua`, so the map must ship its own.
/// Real BAR maps (gecko_isle_remake_v1.2.1, jade_empress_1.3, …) all
/// bundle this two-line bootstrap.
pub const LUAGAIA_MAIN_SOURCE: &str = include_str!("../assets/luagaia_main.lua");

/// LuaGaia draw-context bootstrap. The unsynced-draw context needs
/// its own VFS.Include of the gadget handler so widgets that paint
/// (e.g. mark-renderers) can attach. Bundled at `LuaGaia/draw.lua`.
/// Same verification source as [`LUAGAIA_MAIN_SOURCE`].
pub const LUAGAIA_DRAW_SOURCE: &str = include_str!("../assets/luagaia_draw.lua");

/// Canonical name of BAR's stock geothermal-vent FeatureDef. The
/// `api_resource_spot_finder` upget looks for
/// `FeatureDef.geoThermal = true`, which this name carries; verified
/// against BAR's `sounds/atmos-geovents/` ambience binding + FINDINGS
/// §5. Map-bundled custom geos are Stage 2 (own ADR).
pub const GEOVENT_NAME: &str = "geovent";

/// Render `mapconfig/featureplacer/config.lua` — a one-liner that
/// re-exports `set.lua` so the Springboard gadget's
/// `VFS.Include("mapconfig/featureplacer/config.lua")` call ends up
/// reading our data.
pub fn render_config() -> String {
    "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
     return VFS.Include(\"mapconfig/featureplacer/set.lua\")\n"
        .to_string()
}

/// Render `mapconfig/featureplacer/set.lua` — the actual data the
/// FP_featureplacer gadget consumes: a single table-valued local
/// with `objectlist` / `unitlist` / `buildinglist` keys, returned at
/// the end. C5 populates `objectlist` from `Project.geo_vents`;
/// `unitlist` and `buildinglist` are empty until a map-side-units
/// feature lands (out of scope for Stage 1).
pub fn render_set(project: &Project) -> String {
    let objectlist = LuaValue::Seq(object_entries(project));
    let unitlist = LuaValue::Seq(Vec::new());
    let buildinglist = LuaValue::Seq(Vec::new());
    // We render the local cfg block by hand rather than wrapping it
    // in our LuaValue::Table — preserves the
    // `local setcfg = { ... }; return setcfg` shape that matches
    // existing BAR maps verbatim, so a future map authored in our
    // editor diffs cleanly against a hand-authored one.
    let entries = vec![
        (LuaKey::str("buildinglist"), buildinglist),
        (LuaKey::str("objectlist"), objectlist),
        (LuaKey::str("unitlist"), unitlist),
    ];
    let body = serialize(&LuaValue::Table(entries));
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         local setcfg = {body}\n\
         return setcfg\n"
    )
}

/// Build one entry for the `set.lua` `objectlist`. Rotation is a
/// numeric Lua integer (NOT the quoted-string form PyMapConv's `-k`
/// flag uses) because the gadget calls
/// `Spring.CreateFeature(..., fDef.rot)` which expects a number.
pub(crate) fn feature_entry_int(name: &str, x: i32, z: i32, rot_heading: i16) -> LuaValue {
    LuaValue::Table(vec![
        (LuaKey::str("name"), LuaValue::str(name)),
        (LuaKey::str("rot"), LuaValue::Int(rot_heading as i64)),
        (LuaKey::str("x"), LuaValue::Int(x as i64)),
        (LuaKey::str("z"), LuaValue::Int(z as i64)),
    ])
}

/// Walk `Project.geo_vents` and `Project.features` (in that order) and
/// emit one Lua entry per source.
///
/// **Sort order — deterministic two-section output:**
/// 1. Geo vents first, sorted by `(z, x)`. Matches the C5 / Sprint 11
///    convention; existing tests pin this.
/// 2. User features next, sorted by `(name, z, x)` so a project with
///    one cluster of pines + one cluster of rocks emits a stable
///    grouped diff.
///
/// Putting geos first matches the rule the SRS STATUS UPDATE for
/// Sprint 12 spells out — "emit `Project.geo_vents` first (sorted by
/// xz), THEN `Project.features` (sorted by name then xz). One pass,
/// two sections in source."
///
/// Rotation: geo vents always emit `rot = 0` (the engine samples the
/// gadget at construction with no facing variation); user features
/// emit `feature.rot_heading` cast `as i16` so the wrapping arithmetic
/// preserves the unsigned bit pattern that
/// `Spring.CreateFeature(..., fDef.rot)` consumes. PITFALL §23 — the
/// gadget's rotation arg is numeric, NOT a quoted string (that's
/// PyMapConv's `-k` text-file format, a separate codepath).
fn object_entries(project: &Project) -> Vec<LuaValue> {
    let mut out: Vec<LuaValue> =
        Vec::with_capacity(project.geo_vents.len() + project.features.len());

    // Section 1 — geo vents (Sprint 11 / C5 invariant; sorted by `(z, x)`).
    let mut vents: Vec<GeoVent> = project.geo_vents.clone();
    vents.sort_by_key(|v| (v.z_elmo, v.x_elmo));
    for v in vents {
        out.push(feature_entry_int(GEOVENT_NAME, v.x_elmo, v.z_elmo, 0));
    }

    // Section 2 — user features (Sprint 12 / C6). Sorted by
    // `(name, z, x)` for stable diffs across runs.
    let mut features: Vec<FeatureInstance> = project.features.clone();
    features.sort_by(|a, b| {
        a.name
            .cmp(&b.name)
            .then(a.z_elmo.cmp(&b.z_elmo))
            .then(a.x_elmo.cmp(&b.x_elmo))
    });
    for f in features {
        // Unknown FeatureDef names don't gate the build — the engine
        // logs `[GetFeatureDef] could not find FeatureDef` and skips
        // spawn at load time. C8 (Sprint 14) surfaces this as a
        // pre-emission lint. We still drop a `warn!` for the build
        // log so a stalled smoke test has a clear breadcrumb.
        if !is_known_stock_feature(&f.name) {
            warn!(
                feature_name = %f.name,
                x = f.x_elmo,
                z = f.z_elmo,
                "featureplacer: feature name not in stock manifest — engine will skip spawn unless map bundles its own FeatureDef"
            );
        }
        out.push(feature_entry_int(
            &f.name,
            f.x_elmo,
            f.z_elmo,
            f.rot_heading as i16,
        ));
    }

    out
}

/// Stock-feature membership check. The full catalogue lives at
/// `assets/mapfeatures_catalog.json` and feeds the C6 inspector picker;
/// here we only need to recognise names so the build-time `warn!` is
/// quiet for well-known features. Stage 2 will replace this with a
/// load-once registry shared with the inspector.
///
/// Kept conservatively in-sync with `assets/mapfeatures_catalog.json`.
/// A missing name surfaces as a `warn!` (not a hard failure); the C8
/// lint pass (Sprint 14) is the authoritative gate.
fn is_known_stock_feature(name: &str) -> bool {
    const STOCK: &[&str] = &[
        // trees
        "pinetree",
        "agorm_pine1",
        "agorm_pine2",
        "agorm_pine3",
        "agorm_pine4",
        "agorm_talltree1",
        "agorm_talltree2",
        "agorm_talltree3",
        "agorm_talltree4",
        "agorm_talltree5",
        "agorm_talltree6",
        "btree",
        // rocks
        "rock1",
        "rock2",
        "rock3",
        "rock4",
        "agorm_rock1",
        "agorm_rock2",
        "agorm_rock3",
        // wreckage
        "smallwreck",
        "mediumwreck",
        "largewreck",
        "tankwreck",
        "shipwreck",
        "planewreck",
        // props
        "metalcrate",
        "ruin1",
        "ruin2",
        "deadtree1",
        "deadtree2",
        "antenna",
        "barrel",
        "pillar",
        // geo
        GEOVENT_NAME,
    ];
    STOCK.contains(&name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fp_gadget_is_bundled_with_expected_marker() {
        // `include_str!` would fail to compile if the asset's path
        // wasn't right; this test is a runtime sanity check that the
        // gadget body is what we expect (a contributor moving the
        // asset would catch the failure here).
        assert!(
            FP_GADGET_SOURCE.contains("FP_featureplacer")
                || FP_GADGET_SOURCE.contains("feature placer"),
            "FP_featureplacer.lua asset doesn't look like the Springboard gadget"
        );
        assert!(FP_GADGET_SOURCE.contains("VFS.Include"));
        assert!(FP_GADGET_SOURCE.contains("mapconfig/featureplacer/config.lua"));
        assert!(FP_GADGET_SOURCE.contains("CreateFeature"));
    }

    #[test]
    fn config_redirects_to_set() {
        let s = render_config();
        assert!(s.contains("return VFS.Include"));
        assert!(s.contains("mapconfig/featureplacer/set.lua"));
    }

    #[test]
    fn empty_project_emits_empty_objectlist() {
        let p = Project::new("blank", 4);
        let s = render_set(&p);
        assert!(s.contains("local setcfg ="));
        assert!(s.contains("return setcfg"));
        assert!(s.contains("buildinglist = {}"));
        assert!(s.contains("objectlist = {}"));
        assert!(s.contains("unitlist = {}"));
    }

    /// C5: two geo vents → two `name = "geovent"` entries in
    /// `objectlist`. PITFALL §14 / FINDINGS §5–§6 path verified
    /// against the BAR source.
    #[test]
    fn geo_vents_emit_geovent_objects() {
        let mut p = Project::new("vents", 8);
        p.geo_vents.push(GeoVent::new(2048, 4096));
        p.geo_vents.push(GeoVent::new(2048, 8192));
        let s = render_set(&p);
        let count = s.matches(r#"name = "geovent""#).count();
        assert_eq!(count, 2, "expected 2 geovent entries; got:\n{s}");
        assert!(s.contains("z = 4096"), "got:\n{s}");
        assert!(s.contains("z = 8192"), "got:\n{s}");
        assert!(s.contains("x = 2048"), "got:\n{s}");
    }

    /// Rotation is an UNQUOTED integer in `set.lua` (the gadget
    /// passes it straight to `Spring.CreateFeature(..., fDef.rot)`
    /// which expects a number). Confirmed against a real map
    /// (`gecko_isle_remake_v1.2.1.sd7`'s set.lua uses `rot = -23991`,
    /// not `rot = "-23991"`).
    #[test]
    fn rotation_emits_as_unquoted_integer() {
        let mut p = Project::new("rotint", 8);
        p.geo_vents.push(GeoVent::new(100, 200));
        let s = render_set(&p);
        assert!(
            s.contains("rot = 0,") || s.contains("rot = 0\n"),
            "rot must be an UNQUOTED integer for the Lua gadget path; got:\n{s}"
        );
        assert!(
            !s.contains(r#"rot = "0""#),
            "rot must NOT be a string in set.lua (that's PyMapConv's -k format); got:\n{s}"
        );
    }

    /// Stable diff order: sources are sorted by `(z, x)` even when
    /// authored out-of-order.
    #[test]
    fn geo_vents_emit_sorted_by_z_then_x() {
        let mut p = Project::new("sorted", 8);
        p.geo_vents.push(GeoVent::new(500, 800));
        p.geo_vents.push(GeoVent::new(100, 200));
        p.geo_vents.push(GeoVent::new(900, 200));
        let s = render_set(&p);
        let z200 = s.find("z = 200").expect("z=200 present");
        let z800 = s.find("z = 800").expect("z=800 present");
        assert!(z200 < z800, "smaller-z entries first; got:\n{s}");
    }

    /// Repeat render = byte-identical. Determinism gate for the SD7
    /// archive hash.
    #[test]
    fn render_set_is_deterministic() {
        let mut p = Project::new("det", 4);
        p.geo_vents.push(GeoVent::new(100, 100));
        p.geo_vents.push(GeoVent::new(200, 200));
        let a = render_set(&p);
        let b = render_set(&p);
        assert_eq!(a, b);
    }

    #[test]
    fn render_config_is_deterministic() {
        assert_eq!(render_config(), render_config());
    }

    #[test]
    fn geovent_name_constant_matches_bar_featuredef() {
        assert_eq!(GEOVENT_NAME, "geovent");
    }

    // ─────── C6 (Sprint 12): user features ───────

    /// C6: `Project.features` populate the same `objectlist` as geo
    /// vents do, with the user-supplied `name` and `rot_heading`.
    #[test]
    fn user_features_emit_into_objectlist() {
        use barme_core::FeatureInstance;
        let mut p = Project::new("trees", 8);
        p.features
            .push(FeatureInstance::new("pinetree", 1024, 2048, 0));
        p.features
            .push(FeatureInstance::new("agorm_talltree6", 3000, 4000, 32768));
        let s = render_set(&p);
        assert!(s.contains(r#"name = "pinetree""#), "got:\n{s}");
        assert!(s.contains(r#"name = "agorm_talltree6""#), "got:\n{s}");
    }

    /// C6: rotation emits as an UNQUOTED integer (PITFALL §23 — the
    /// gadget calls `Spring.CreateFeature(..., fDef.rot)` which
    /// expects a number; PyMapConv's `-k` flat-text format that uses
    /// quoted strings is a different codepath we don't ship). Pin
    /// the wrap-through-i16 cast: rot_heading = 32768 (mid-circle
    /// unsigned) → `rot = -32768,` (wrapping cast to signed 16-bit).
    #[test]
    fn renders_features_with_quoted_rot_emits_as_int_not_string() {
        use barme_core::FeatureInstance;
        let mut p = Project::new("rot", 4);
        p.features
            .push(FeatureInstance::new("pinetree", 100, 200, 0));
        p.features
            .push(FeatureInstance::new("rock1", 300, 400, 32768));
        let s = render_set(&p);
        // Unquoted integer form — PITFALL §23.
        assert!(
            s.contains("rot = 0,") || s.contains("rot = 0\n"),
            "pinetree rot must be UNQUOTED int 0; got:\n{s}"
        );
        // rot_heading = 32768 unsigned → -32768 as i16 (bit pattern
        // preserved through Lua → Spring.CreateFeature).
        assert!(
            s.contains("rot = -32768,") || s.contains("rot = -32768\n"),
            "rock1 rot must wrap u16=32768 to i16=-32768; got:\n{s}"
        );
        // No string-form anywhere — guards against C2 / PyMapConv `-k`
        // format leaking into the gadget path.
        assert!(
            !s.contains(r#"rot = ""#),
            "rot must never be quoted in set.lua (PITFALL §23); got:\n{s}"
        );
    }

    /// C6: geo vents AND user features coexist in `objectlist` —
    /// geos first sorted by (z, x), then features sorted by
    /// (name, z, x). Order is deterministic for NFR-Det.
    #[test]
    fn geo_and_user_features_coexist() {
        use barme_core::FeatureInstance;
        let mut p = Project::new("mixed", 8);
        p.geo_vents.push(GeoVent::new(100, 200));
        p.geo_vents.push(GeoVent::new(500, 100));
        p.features
            .push(FeatureInstance::new("pinetree", 100, 100, 0));
        p.features.push(FeatureInstance::new("rock1", 200, 200, 0));
        let s = render_set(&p);
        // All four entries present.
        assert_eq!(s.matches(r#"name = "geovent""#).count(), 2);
        assert_eq!(s.matches(r#"name = "pinetree""#).count(), 1);
        assert_eq!(s.matches(r#"name = "rock1""#).count(), 1);
        // Section order: geovents block first, then user features.
        let p_first_geo = s.find(r#"name = "geovent""#).unwrap();
        let p_first_user = s
            .find(r#"name = "pinetree""#)
            .min(s.find(r#"name = "rock1""#).unwrap_or(usize::MAX).into())
            .unwrap_or_else(|| s.find(r#"name = "pinetree""#).unwrap());
        assert!(
            p_first_geo < p_first_user,
            "geo vents must emit before user features; got:\n{s}"
        );
        // Within user features, alphabetic order by name → pinetree
        // (p) sorts before rock1 (r).
        let p_pine = s.find(r#"name = "pinetree""#).unwrap();
        let p_rock = s.find(r#"name = "rock1""#).unwrap();
        assert!(
            p_pine < p_rock,
            "user features must be sorted by name; got:\n{s}"
        );
    }

    /// C6: the stock manifest membership check finds the canonical
    /// geovent name (so it doesn't trip the unknown-feature warn).
    #[test]
    fn stock_geovent_present_in_manifest_check() {
        assert!(is_known_stock_feature(GEOVENT_NAME));
        assert!(is_known_stock_feature("pinetree"));
        assert!(is_known_stock_feature("agorm_talltree6"));
        assert!(is_known_stock_feature("rock1"));
        // A made-up name fails the check.
        assert!(!is_known_stock_feature("not_a_real_feature"));
        assert!(!is_known_stock_feature(""));
    }

    /// C6: empty geos + empty features still produces a well-formed
    /// `objectlist = {}` (no spurious section markers).
    #[test]
    fn empty_geos_and_features_render_empty_objectlist() {
        let p = Project::new("blank", 4);
        let s = render_set(&p);
        assert!(s.contains("objectlist = {}"), "got:\n{s}");
    }

    /// C6: features sort stably across renders — repeat render =
    /// byte-identical (NFR-Determinism).
    #[test]
    fn features_render_deterministically_across_repeated_calls() {
        use barme_core::FeatureInstance;
        let mut p = Project::new("det", 4);
        // Push in non-sorted insertion order.
        p.features.push(FeatureInstance::new("rock1", 500, 100, 0));
        p.features
            .push(FeatureInstance::new("pinetree", 100, 500, 0));
        p.features
            .push(FeatureInstance::new("pinetree", 100, 100, 0));
        let a = render_set(&p);
        let b = render_set(&p);
        assert_eq!(a, b, "non-deterministic emit");
        // Within the same `name`, sorted by (z, x): the (100, 100)
        // pine emits before the (100, 500) pine.
        let pos_100_100 = a.find("z = 100,").unwrap();
        let pos_100_500 = a.find("z = 500,").unwrap();
        assert!(pos_100_100 < pos_100_500, "got:\n{a}");
    }
}
