//! Minimum-viable `mapinfo.lua` emitter (ADR-013).
//!
//! Hand-rolled string formatter, **not** a Lua AST. The full AST will live in
//! a future `barme-mapinfo` crate when the editor UI needs to round-trip
//! handwritten mapinfo files (Stage 1+); for v0 we only need to produce a
//! file the engine accepts.
//!
//! The emitter pins `smtFileName0 = "maps/<name>.smt"` derived from the same
//! `name` field the SMT is written with — PITFALL #7 (pink-map on rename) is
//! defended at the source.
//!
//! Field set is the *documented minimum* (per the BAR map-format reference
//! gist at `burnhamrobertp/97cae4d300e675ca261e661fc58266d1`): `name`,
//! `smf.smtFileName0`, and `teams[].startPos` are the only required keys.
//! `modtype = 3` is also pinned because Chobby's map-browser filter
//! (`gui_maplist_panel.lua`) requires it. Everything else has engine defaults.

use barme_core::Project;
#[cfg(test)]
use barme_core::StartPosition;

/// Render a `mapinfo.lua` for the given project.
///
/// The output is deterministic given the same inputs (no timestamps, no
/// random tags).
///
/// `teams[]` is emitted from `project.start_positions` when non-empty.
/// When empty, two positions are auto-generated at 25%/75% along the map
/// diagonal — sufficient for the engine to compute a sensible default
/// camera and let a 1v1 skirmish actually start. F8 / ADR-023.
pub fn render(project: &Project) -> String {
    let name = lua_string(&project.name);
    let smf_name = lua_string(&format!("maps/{}.smf", project.name));
    let smt_name = lua_string(&format!("maps/{}.smt", project.name));
    let min_h = project.min_height.round() as i64;
    let max_h = project.max_height.round() as i64;

    let teams_body = render_teams(project);

    format!(
        r#"-- Auto-generated by barme-pipeline (ADR-013); do not hand-edit.
local mapinfo = {{
    name        = {name},
    shortname   = {name},
    description = "",
    version     = "1",
    mapfile     = {smf_name},
    modtype     = 3,
    depend      = {{ "Map Helper v1" }},

    smf = {{
        minheight    = {min_h},
        maxheight    = {max_h},
        smtFileName0 = {smt_name},
    }},

    teams = {{
{teams_body}    }},

    -- BAR's `luarules/gadgets/unit_sunfacing.lua` does
    -- `mapinfo.lighting.sundir` with no nil check. Engine has defaults
    -- for the lighting section but BAR-mod gadgets read it directly,
    -- so the block must exist. {{x, y, z}} where +y is up; mild SE sun.
    lighting = {{
        sundir = {{ 0.3, 1.0, -0.2 }},
    }},
}}

return mapinfo
"#
    )
}

/// Emit the `teams[]` table body. Each entry is one indented line. Either
/// the project's authored start positions (sorted by team id, deterministic
/// output) or a 25/75 diagonal default for unfilled projects.
fn render_teams(project: &Project) -> String {
    let mut out = String::new();
    if project.start_positions.is_empty() {
        let (ex, ez) = project.size.elmo_extents();
        let (x0, z0) = (ex / 4, ez / 4);
        let (x1, z1) = (ex * 3 / 4, ez * 3 / 4);
        out.push_str(&format!(
            "        [0] = {{ startPos = {{ x = {x0}, z = {z0} }} }},\n"
        ));
        out.push_str(&format!(
            "        [1] = {{ startPos = {{ x = {x1}, z = {z1} }} }},\n"
        ));
        return out;
    }
    let mut sorted: Vec<_> = project.start_positions.iter().collect();
    sorted.sort_by_key(|p| p.team_id);
    for p in sorted {
        out.push_str(&format!(
            "        [{id}] = {{ startPos = {{ x = {x}, z = {z} }} }},\n",
            id = p.team_id,
            x = p.x_elmo,
            z = p.z_elmo,
        ));
    }
    out
}

/// Quote a string safely as a Lua literal — escape `"` and `\` only. Project
/// names are sanitized at the UI / load layer; this is defence-in-depth so a
/// surprising character can't break the Lua parser silently.
fn lua_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_with_name_and_heights() {
        let mut p = Project::new("alpha", 4);
        p.min_height = -50.0;
        p.max_height = 500.0;
        let s = render(&p);
        assert!(s.contains(r#"name        = "alpha""#));
        assert!(s.contains(r#"smtFileName0 = "maps/alpha.smt""#));
        assert!(s.contains("minheight    = -50"));
        assert!(s.contains("maxheight    = 500"));
    }

    #[test]
    fn teams_scale_with_map_size() {
        // 8 SMU = 4096 elmos per side. 25% / 75% diagonal: 1024 / 3072.
        let p = Project::new("duel", 8);
        let s = render(&p);
        assert!(
            s.contains("[0] = { startPos = { x = 1024, z = 1024 } }"),
            "team 0 missing or wrong, got:\n{s}"
        );
        assert!(
            s.contains("[1] = { startPos = { x = 3072, z = 3072 } }"),
            "team 1 missing or wrong, got:\n{s}"
        );
    }

    #[test]
    fn includes_lighting_block_for_bar_mod_gadgets() {
        // BAR's unit_sunfacing.lua crashes on missing `lighting.sundir`.
        // Catch a regression where someone "simplifies" the emitter back
        // to the engine-documented minimum and re-introduces the crash.
        let p = Project::new("smoke", 4);
        let s = render(&p);
        assert!(s.contains("lighting = {"), "lighting block missing");
        assert!(s.contains("sundir"), "lighting.sundir missing");
    }

    #[test]
    fn lua_string_escapes_quotes_and_backslashes() {
        assert_eq!(lua_string(r#"hello"world"#), r#""hello\"world""#);
        assert_eq!(lua_string(r"path\to\file"), r#""path\\to\\file""#);
    }

    #[test]
    fn authored_start_positions_replace_default_pair() {
        let mut p = Project::new("teams", 8);
        p.start_positions = vec![
            StartPosition {
                team_id: 0,
                x_elmo: 500,
                z_elmo: 600,
            },
            StartPosition {
                team_id: 1,
                x_elmo: 1500,
                z_elmo: 1600,
            },
            StartPosition {
                team_id: 2,
                x_elmo: 2500,
                z_elmo: 2600,
            },
        ];
        let s = render(&p);
        assert!(s.contains("[0] = { startPos = { x = 500, z = 600 } }"));
        assert!(s.contains("[1] = { startPos = { x = 1500, z = 1600 } }"));
        assert!(s.contains("[2] = { startPos = { x = 2500, z = 2600 } }"));
        // The 25/75 default must not appear when authored positions exist.
        assert!(!s.contains("x = 1024, z = 1024"));
    }

    #[test]
    fn teams_are_sorted_for_deterministic_output() {
        let mut p = Project::new("teams", 4);
        p.start_positions = vec![
            StartPosition {
                team_id: 3,
                x_elmo: 100,
                z_elmo: 100,
            },
            StartPosition {
                team_id: 0,
                x_elmo: 200,
                z_elmo: 200,
            },
            StartPosition {
                team_id: 1,
                x_elmo: 300,
                z_elmo: 300,
            },
        ];
        let s = render(&p);
        let p0 = s.find("[0] =").unwrap();
        let p1 = s.find("[1] =").unwrap();
        let p3 = s.find("[3] =").unwrap();
        assert!(p0 < p1 && p1 < p3, "team rows must be sorted by id");
    }

    #[test]
    fn smt_filename_always_matches_project_name() {
        // PITFALL #7 — the emitter and the SMT writer share a single
        // `project.name` source; this test pins that contract.
        let p = Project::new("smoke", 2);
        let s = render(&p);
        assert!(s.contains(r#"smtFileName0 = "maps/smoke.smt""#));
        assert!(s.contains(r#"mapfile     = "maps/smoke.smf""#));
    }
}
