//! Minimum-viable `mapinfo.lua` emitter (ADR-013).
//!
//! Hand-rolled string formatter, **not** a Lua AST. The full AST will live in
//! a future `barme-mapinfo` crate when the editor UI needs to round-trip
//! handwritten mapinfo files (Stage 1+); for v0 we only need to produce a
//! file the engine accepts.
//!
//! The emitter pins `smtFileName0 = "maps/<name>.smt"` derived from the same
//! `name` field the SMT is written with — PITFALL #7 (pink-map on rename) is
//! defended at the source.
//!
//! Field set is the *documented minimum* (per the BAR map-format reference
//! gist at `burnhamrobertp/97cae4d300e675ca261e661fc58266d1`): `name`,
//! `smf.smtFileName0`, and `teams[].startPos` are the only required keys.
//! `modtype = 3` is also pinned because Chobby's map-browser filter
//! (`gui_maplist_panel.lua`) requires it. Everything else has engine defaults.

use barme_core::Project;

/// Render a `mapinfo.lua` for the given project.
///
/// The output is deterministic given the same inputs (no timestamps, no
/// random tags).
///
/// Two start positions are auto-generated at 25%/75% along the map diagonal
/// — sufficient for the engine to compute a sensible default camera and
/// let a 1v1 skirmish actually start. Authoring custom teams is a Stage 1
/// concern.
pub fn render(project: &Project) -> String {
    let name = lua_string(&project.name);
    let smf_name = lua_string(&format!("maps/{}.smf", project.name));
    let smt_name = lua_string(&format!("maps/{}.smt", project.name));
    let min_h = project.min_height.round() as i64;
    let max_h = project.max_height.round() as i64;

    let (ex, ez) = project.size.elmo_extents();
    let (x0, z0) = (ex / 4, ez / 4);
    let (x1, z1) = (ex * 3 / 4, ez * 3 / 4);

    format!(
        r#"-- Auto-generated by barme-pipeline (ADR-013); do not hand-edit.
local mapinfo = {{
    name        = {name},
    shortname   = {name},
    description = "",
    version     = "1",
    mapfile     = {smf_name},
    modtype     = 3,
    depend      = {{ "Map Helper v1" }},

    smf = {{
        minheight    = {min_h},
        maxheight    = {max_h},
        smtFileName0 = {smt_name},
    }},

    teams = {{
        [0] = {{ startPos = {{ x = {x0}, z = {z0} }} }},
        [1] = {{ startPos = {{ x = {x1}, z = {z1} }} }},
    }},

    -- BAR's `luarules/gadgets/unit_sunfacing.lua` does
    -- `mapinfo.lighting.sundir` with no nil check. Engine has defaults
    -- for the lighting section but BAR-mod gadgets read it directly,
    -- so the block must exist. {{x, y, z}} where +y is up; mild SE sun.
    lighting = {{
        sundir = {{ 0.3, 1.0, -0.2 }},
    }},
}}

return mapinfo
"#
    )
}

/// Quote a string safely as a Lua literal — escape `"` and `\` only. Project
/// names are sanitized at the UI / load layer; this is defence-in-depth so a
/// surprising character can't break the Lua parser silently.
fn lua_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_with_name_and_heights() {
        let mut p = Project::new("alpha", 4);
        p.min_height = -50.0;
        p.max_height = 500.0;
        let s = render(&p);
        assert!(s.contains(r#"name        = "alpha""#));
        assert!(s.contains(r#"smtFileName0 = "maps/alpha.smt""#));
        assert!(s.contains("minheight    = -50"));
        assert!(s.contains("maxheight    = 500"));
    }

    #[test]
    fn teams_scale_with_map_size() {
        // 8 SMU = 4096 elmos per side. 25% / 75% diagonal: 1024 / 3072.
        let p = Project::new("duel", 8);
        let s = render(&p);
        assert!(
            s.contains("[0] = { startPos = { x = 1024, z = 1024 } }"),
            "team 0 missing or wrong, got:\n{s}"
        );
        assert!(
            s.contains("[1] = { startPos = { x = 3072, z = 3072 } }"),
            "team 1 missing or wrong, got:\n{s}"
        );
    }

    #[test]
    fn includes_lighting_block_for_bar_mod_gadgets() {
        // BAR's unit_sunfacing.lua crashes on missing `lighting.sundir`.
        // Catch a regression where someone "simplifies" the emitter back
        // to the engine-documented minimum and re-introduces the crash.
        let p = Project::new("smoke", 4);
        let s = render(&p);
        assert!(s.contains("lighting = {"), "lighting block missing");
        assert!(s.contains("sundir"), "lighting.sundir missing");
    }

    #[test]
    fn lua_string_escapes_quotes_and_backslashes() {
        assert_eq!(lua_string(r#"hello"world"#), r#""hello\"world""#);
        assert_eq!(lua_string(r"path\to\file"), r#""path\\to\\file""#);
    }

    #[test]
    fn smt_filename_always_matches_project_name() {
        // PITFALL #7 — the emitter and the SMT writer share a single
        // `project.name` source; this test pins that contract.
        let p = Project::new("smoke", 2);
        let s = render(&p);
        assert!(s.contains(r#"smtFileName0 = "maps/smoke.smt""#));
        assert!(s.contains(r#"mapfile     = "maps/smoke.smf""#));
    }
}
