//! `mapinfo.lua` emitter via the Lua AST (ADR-029, supersedes ADR-013).
//!
//! Consumes [`barme_core::MapInfo`] (the typed schema, ADR-028) and
//! emits the canonical
//! `-- Auto-generated …\nlocal mapinfo = { … }\nreturn mapinfo` text
//! every BAR map ships. The schema's `From<&Project>` conversion does
//! the data assembly; this module only translates between schema
//! structs and [`crate::lua_ast::LuaValue`] trees.
//!
//! ## Key naming
//!
//! Rust uses snake_case; BAR Lua uses camelCase (with a few historic
//! lowercase exceptions like `maphardness`). The per-block helpers
//! below pin every Lua key explicitly — no auto-conversion that could
//! drift behind a community-style guide change. The mapping table is
//! tested implicitly via the golden-string assertions at the bottom.
//!
//! ## Determinism (NFR-Det)
//!
//! Every keyed table is sorted via [`sort_table_by_key`] before
//! emission. Sequence tables preserve their input order — callers
//! choose order deliberately (e.g. `teams[]` is built in increasing
//! index order; `terrain_types` walks the input vec).
//!
//! ## Empty-teams fallback
//!
//! Pre-F8 projects (and current `Project` defaults when the user
//! hasn't placed anything) carry no start positions. The engine
//! requires at least one `teams[*].startPos` — without it, the lobby
//! shows `0/0` and "waiting for players" hangs. The emitter falls
//! back to the 25 % / 75 % diagonal pair so blank projects still
//! build a playable 1v1 map. See PITFALL §teams[] count.

use barme_core::{LightingBlock, MapInfo, Project, SmfBlock, SunDir, TeamBlock};

use crate::lua_ast::{LuaKey, LuaValue, serialize, sort_table_by_key};

/// Render a `mapinfo.lua` for the given project.
///
/// Output is deterministic for the same input (no timestamps; tables
/// alphabetically keyed). On empty `teams[]`, the 25/75 default pair
/// is materialised before emission.
pub fn render(project: &Project) -> String {
    let mut info: MapInfo = project.into();
    if info.teams.is_empty() {
        info.teams = default_team_pair(project);
    }
    render_mapinfo(&info)
}

/// Render a populated [`MapInfo`] to the canonical Lua text. This is
/// the AST-level entry point — used directly by tests and by callers
/// that want to bypass the empty-teams fallback.
pub fn render_mapinfo(info: &MapInfo) -> String {
    let v = build_mapinfo(info);
    let body = serialize(&v);
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         local mapinfo = {body}\n\
         \n\
         return mapinfo\n"
    )
}

// ─────── per-block builders ───────

fn build_mapinfo(info: &MapInfo) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();

    // Scalars.
    t.push((LuaKey::str("name"), LuaValue::str(&info.name)));
    if let Some(s) = &info.shortname {
        t.push((LuaKey::str("shortname"), LuaValue::str(s)));
    }
    if let Some(s) = &info.description {
        t.push((LuaKey::str("description"), LuaValue::str(s)));
    }
    if let Some(s) = &info.author {
        t.push((LuaKey::str("author"), LuaValue::str(s)));
    }
    t.push((LuaKey::str("version"), LuaValue::str(&info.version)));
    t.push((LuaKey::str("mapfile"), LuaValue::str(&info.mapfile)));
    t.push((LuaKey::str("modtype"), LuaValue::Int(info.modtype as i64)));
    if !info.depend.is_empty() {
        t.push((LuaKey::str("depend"), str_seq(&info.depend)));
    }
    if !info.replace.is_empty() {
        t.push((LuaKey::str("replace"), str_seq(&info.replace)));
    }
    if let Some(v) = info.maphardness {
        t.push((LuaKey::str("maphardness"), LuaValue::Float(v as f64)));
    }
    if let Some(v) = info.not_deformable {
        t.push((LuaKey::str("notDeformable"), LuaValue::Bool(v)));
    }
    if let Some(v) = info.gravity {
        t.push((LuaKey::str("gravity"), LuaValue::Float(v as f64)));
    }
    if let Some(v) = info.tidal_strength {
        t.push((LuaKey::str("tidalStrength"), LuaValue::Float(v as f64)));
    }
    if let Some(v) = info.max_metal {
        t.push((LuaKey::str("maxMetal"), LuaValue::Float(v as f64)));
    }
    if let Some(v) = info.extractor_radius {
        t.push((LuaKey::str("extractorRadius"), LuaValue::Float(v as f64)));
    }
    if info.void_water {
        t.push((LuaKey::str("voidWater"), LuaValue::Bool(true)));
    }
    if info.void_ground {
        t.push((LuaKey::str("voidGround"), LuaValue::Bool(true)));
    }
    if let Some(v) = info.auto_show_metal {
        t.push((LuaKey::str("autoShowMetal"), LuaValue::Bool(v)));
    }

    // Sub-tables.
    t.push((LuaKey::str("smf"), smf_block(&info.smf)));
    t.push((LuaKey::str("lighting"), lighting_block(&info.lighting)));
    t.push((
        LuaKey::str("atmosphere"),
        atmosphere_block(&info.atmosphere),
    ));
    if let Some(w) = &info.water {
        t.push((LuaKey::str("water"), water_block(w)));
    }
    t.push((LuaKey::str("splats"), splats_block(&info.splats)));
    t.push((LuaKey::str("resources"), resources_block(&info.resources)));
    if !info.terrain_types.is_empty() {
        t.push((
            LuaKey::str("terrainTypes"),
            terrain_types_block(&info.terrain_types),
        ));
    }
    if let Some(g) = &info.grass {
        t.push((LuaKey::str("grass"), grass_block(g)));
    }
    if !info.teams.is_empty() {
        t.push((LuaKey::str("teams"), teams_block(&info.teams)));
    }
    if let Some(s) = &info.sound {
        t.push((LuaKey::str("sound"), sound_block(s)));
    }
    if let Some(g) = &info.gui {
        t.push((LuaKey::str("gui"), gui_block(g)));
    }
    // custom is a free-form bag; emit a placeholder empty table so
    // gadgets reading `mapinfo.custom.fog` etc. get nil rather than a
    // crash on `index a nil value`. (The schema's custom HashMap is
    // toml::Value-shaped; full serialisation is C7's job when F9 lets
    // the user author entries.)
    if !info.custom.is_empty() {
        t.push((LuaKey::str("custom"), LuaValue::Table(vec![])));
    }

    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn smf_block(b: &SmfBlock) -> LuaValue {
    let mut t = vec![(
        LuaKey::str("smtFileName0"),
        LuaValue::str(&b.smt_file_name_0),
    )];
    if let Some(h) = b.min_height {
        t.push((LuaKey::str("minHeight"), LuaValue::Float(h as f64)));
    }
    if let Some(h) = b.max_height {
        t.push((LuaKey::str("maxHeight"), LuaValue::Float(h as f64)));
    }
    if let Some(s) = &b.minimap_tex {
        t.push((LuaKey::str("minimapTex"), LuaValue::str(s)));
    }
    for (i, name) in b.smt_file_name_extras.iter().enumerate() {
        t.push((
            LuaKey::str(format!("smtFileName{}", i + 1)),
            LuaValue::str(name),
        ));
    }
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn lighting_block(b: &LightingBlock) -> LuaValue {
    let mut t = vec![(LuaKey::str("sunDir"), sundir(b.sun_dir))];
    push_rgb(&mut t, "groundAmbientColor", b.ground_ambient_color);
    push_rgb(&mut t, "groundDiffuseColor", b.ground_diffuse_color);
    push_rgb(&mut t, "groundSpecularColor", b.ground_specular_color);
    push_f32(&mut t, "groundShadowDensity", b.ground_shadow_density);
    push_rgb(&mut t, "unitAmbientColor", b.unit_ambient_color);
    push_rgb(&mut t, "unitDiffuseColor", b.unit_diffuse_color);
    push_rgb(&mut t, "unitSpecularColor", b.unit_specular_color);
    push_f32(&mut t, "unitShadowDensity", b.unit_shadow_density);
    push_f32(&mut t, "specularExponent", b.specular_exponent);
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn atmosphere_block(b: &barme_core::AtmosphereBlock) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();
    push_f32(&mut t, "minWind", b.min_wind);
    push_f32(&mut t, "maxWind", b.max_wind);
    push_f32(&mut t, "fogStart", b.fog_start);
    push_f32(&mut t, "fogEnd", b.fog_end);
    push_rgb(&mut t, "fogColor", b.fog_color);
    push_rgb(&mut t, "sunColor", b.sun_color);
    push_rgb(&mut t, "skyColor", b.sky_color);
    push_rgb(&mut t, "skyDir", b.sky_dir);
    if let Some(s) = &b.sky_box {
        t.push((LuaKey::str("skyBox"), LuaValue::str(s)));
    }
    push_f32(&mut t, "cloudDensity", b.cloud_density);
    push_rgb(&mut t, "cloudColor", b.cloud_color);
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn water_block(b: &barme_core::WaterBlock) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();
    push_f32(&mut t, "damage", b.damage);
    push_f32(&mut t, "repeatX", b.repeat_x);
    push_f32(&mut t, "repeatY", b.repeat_y);
    push_rgb(&mut t, "surfaceColor", b.surface_color);
    push_rgb(&mut t, "planeColor", b.plane_color);
    push_rgb(&mut t, "absorb", b.absorb);
    push_rgb(&mut t, "baseColor", b.base_color);
    push_rgb(&mut t, "minColor", b.min_color);
    push_f32(&mut t, "ambientFactor", b.ambient_factor);
    push_f32(&mut t, "diffuseFactor", b.diffuse_factor);
    push_f32(&mut t, "specularFactor", b.specular_factor);
    push_rgb(&mut t, "specularColor", b.specular_color);
    push_f32(&mut t, "specularPower", b.specular_power);
    push_f32(&mut t, "fresnelMin", b.fresnel_min);
    push_f32(&mut t, "fresnelMax", b.fresnel_max);
    push_f32(&mut t, "fresnelPower", b.fresnel_power);
    push_f32(&mut t, "reflectionDistortion", b.reflection_distortion);
    push_f32(&mut t, "blurBase", b.blur_base);
    push_f32(&mut t, "blurExponent", b.blur_exponent);
    push_f32(&mut t, "perlinStartFreq", b.perlin_start_freq);
    push_f32(&mut t, "perlinLacunarity", b.perlin_lacunarity);
    push_f32(&mut t, "perlinAmplitude", b.perlin_amplitude);
    if let Some(n) = b.num_tiles {
        t.push((LuaKey::str("numTiles"), LuaValue::Int(n as i64)));
    }
    if let Some(b2) = b.shore_waves {
        t.push((LuaKey::str("shoreWaves"), LuaValue::Bool(b2)));
    }
    if let Some(b2) = b.force_rendering {
        t.push((LuaKey::str("forceRendering"), LuaValue::Bool(b2)));
    }
    if let Some(s) = &b.texture {
        t.push((LuaKey::str("texture"), LuaValue::str(s)));
    }
    if let Some(s) = &b.foam_texture {
        t.push((LuaKey::str("foamTexture"), LuaValue::str(s)));
    }
    if let Some(s) = &b.normal_texture {
        t.push((LuaKey::str("normalTexture"), LuaValue::str(s)));
    }
    if !b.caustics.is_empty() {
        t.push((LuaKey::str("caustics"), str_seq(&b.caustics)));
    }
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn splats_block(b: &barme_core::SplatsBlock) -> LuaValue {
    let scales = LuaValue::Seq(
        b.tex_scales
            .iter()
            .map(|&f| LuaValue::Float(f as f64))
            .collect(),
    );
    let mults = LuaValue::Seq(
        b.tex_mults
            .iter()
            .map(|&f| LuaValue::Float(f as f64))
            .collect(),
    );
    let mut t = vec![
        (LuaKey::str("texScales"), scales),
        (LuaKey::str("texMults"), mults),
    ];
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn resources_block(b: &barme_core::ResourcesBlock) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();
    push_str_opt(&mut t, "detailTex", b.detail_tex.as_deref());
    push_str_opt(&mut t, "specularTex", b.specular_tex.as_deref());
    push_str_opt(&mut t, "splatDetailTex", b.splat_detail_tex.as_deref());
    push_str_opt(&mut t, "splatDistrTex", b.splat_distr_tex.as_deref());
    if !b.splat_detail_normal_tex.is_empty() {
        t.push((
            LuaKey::str("splatDetailNormalTex"),
            str_seq(&b.splat_detail_normal_tex),
        ));
    }
    if let Some(v) = b.splat_detail_normal_diffuse_alpha {
        t.push((
            LuaKey::str("splatDetailNormalDiffuseAlpha"),
            LuaValue::Int(v as i64),
        ));
    }
    push_str_opt(&mut t, "skyReflectModTex", b.sky_reflect_mod_tex.as_deref());
    push_str_opt(&mut t, "detailNormalTex", b.detail_normal_tex.as_deref());
    push_str_opt(&mut t, "lightEmissionTex", b.light_emission_tex.as_deref());
    push_str_opt(
        &mut t,
        "parallaxHeightTex",
        b.parallax_height_tex.as_deref(),
    );
    push_str_opt(&mut t, "grassBladeTex", b.grass_blade_tex.as_deref());
    push_str_opt(&mut t, "grassShadingTex", b.grass_shading_tex.as_deref());
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn terrain_types_block(types: &[barme_core::TerrainTypeBlock]) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::with_capacity(types.len());
    for tt in types {
        let mut inner: Vec<(LuaKey, LuaValue)> = Vec::new();
        if let Some(n) = &tt.name {
            inner.push((LuaKey::str("name"), LuaValue::str(n)));
        }
        push_f32(&mut inner, "hardness", tt.hardness);
        if let Some(b) = tt.receive_tracks {
            inner.push((LuaKey::str("receiveTracks"), LuaValue::Bool(b)));
        }
        if let Some(ms) = &tt.move_speeds {
            let mut speeds: Vec<(LuaKey, LuaValue)> = Vec::new();
            push_f32(&mut speeds, "tank", ms.tank);
            push_f32(&mut speeds, "kbot", ms.kbot);
            push_f32(&mut speeds, "hover", ms.hover);
            push_f32(&mut speeds, "ship", ms.ship);
            if !speeds.is_empty() {
                sort_table_by_key(&mut speeds);
                inner.push((LuaKey::str("moveSpeeds"), LuaValue::Table(speeds)));
            }
        }
        sort_table_by_key(&mut inner);
        t.push((LuaKey::int(tt.index as i64), LuaValue::Table(inner)));
    }
    // Integer-keyed; sort numerically.
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn grass_block(b: &barme_core::GrassBlock) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();
    push_f32(&mut t, "bladeWidth", b.blade_width);
    push_f32(&mut t, "bladeHeight", b.blade_height);
    push_f32(&mut t, "bladeAngle", b.blade_angle);
    push_rgb(&mut t, "bladeColor", b.blade_color);
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn teams_block(teams: &[TeamBlock]) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::with_capacity(teams.len());
    for (i, tb) in teams.iter().enumerate() {
        let mut sp = vec![
            (LuaKey::str("x"), LuaValue::Int(tb.start_pos.x as i64)),
            (LuaKey::str("z"), LuaValue::Int(tb.start_pos.z as i64)),
        ];
        sort_table_by_key(&mut sp);
        let entry = LuaValue::Table(vec![(LuaKey::str("startPos"), LuaValue::Table(sp))]);
        t.push((LuaKey::int(i as i64), entry));
    }
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn sound_block(b: &barme_core::SoundBlock) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();
    if let Some(s) = &b.preset {
        t.push((LuaKey::str("preset"), LuaValue::str(s)));
    }
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

fn gui_block(b: &barme_core::GuiBlock) -> LuaValue {
    let mut t: Vec<(LuaKey, LuaValue)> = Vec::new();
    if let Some(n) = b.minimap_rotation {
        t.push((LuaKey::str("minimapRotation"), LuaValue::Int(n as i64)));
    }
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

// ─────── small helpers ───────

fn str_seq(items: &[String]) -> LuaValue {
    LuaValue::Seq(items.iter().map(LuaValue::str).collect())
}

fn sundir(d: SunDir) -> LuaValue {
    LuaValue::Seq(d.iter().map(|&f| LuaValue::Float(f as f64)).collect())
}

fn rgb(c: [f32; 3]) -> LuaValue {
    LuaValue::Seq(c.iter().map(|&f| LuaValue::Float(f as f64)).collect())
}

fn push_rgb(t: &mut Vec<(LuaKey, LuaValue)>, key: &str, v: Option<[f32; 3]>) {
    if let Some(c) = v {
        t.push((LuaKey::str(key), rgb(c)));
    }
}

fn push_f32(t: &mut Vec<(LuaKey, LuaValue)>, key: &str, v: Option<f32>) {
    if let Some(f) = v {
        t.push((LuaKey::str(key), LuaValue::Float(f as f64)));
    }
}

fn push_str_opt(t: &mut Vec<(LuaKey, LuaValue)>, key: &str, v: Option<&str>) {
    if let Some(s) = v {
        t.push((LuaKey::str(key), LuaValue::str(s)));
    }
}

/// 25 % / 75 % diagonal default pair for a blank `teams[]`. Matches
/// ADR-013's behaviour so pre-F8 projects still produce a playable
/// 1v1 archive after the C2 refactor.
fn default_team_pair(project: &Project) -> Vec<TeamBlock> {
    use barme_core::TeamStartPos;
    let (ex, ez) = project.size.elmo_extents();
    let (x0, z0) = (ex as i32 / 4, ez as i32 / 4);
    let (x1, z1) = (ex as i32 * 3 / 4, ez as i32 * 3 / 4);
    vec![
        TeamBlock {
            start_pos: TeamStartPos { x: x0, z: z0 },
        },
        TeamBlock {
            start_pos: TeamStartPos { x: x1, z: z1 },
        },
    ]
}

#[cfg(test)]
mod tests {
    use super::*;
    use barme_core::StartPosition;

    #[test]
    fn renders_with_name_and_heights() {
        let mut p = Project::new("alpha", 4);
        p.min_height = -50.0;
        p.max_height = 500.0;
        let s = render(&p);
        assert!(s.contains(r#"name = "alpha","#), "got:\n{s}");
        assert!(
            s.contains(r#"smtFileName0 = "maps/alpha.smt","#),
            "got:\n{s}"
        );
        assert!(s.contains("minHeight = -50.0"), "got:\n{s}");
        assert!(s.contains("maxHeight = 500.0"), "got:\n{s}");
    }

    #[test]
    fn teams_scale_with_map_size_when_empty() {
        // 8 SMU = 4096 elmos per side. 25% / 75% diagonal: 1024 / 3072.
        let p = Project::new("duel", 8);
        let s = render(&p);
        assert!(
            s.contains("[0] = {\n      startPos = {\n        x = 1024,\n        z = 1024,"),
            "team 0 not rendered with expected coords; got:\n{s}"
        );
        assert!(
            s.contains("[1] = {\n      startPos = {\n        x = 3072,\n        z = 3072,"),
            "team 1 not rendered with expected coords; got:\n{s}"
        );
    }

    #[test]
    fn includes_lighting_sundir_for_bar_mod_gadgets() {
        let p = Project::new("smoke", 4);
        let s = render(&p);
        assert!(s.contains("lighting = {"), "lighting block missing");
        assert!(s.contains("sunDir = {"), "lighting.sunDir missing");
        // sunDir must be a 4-component vector (vec3 + sunStart).
        let snippet = &s[s.find("sunDir").unwrap()..];
        let close = snippet.find('}').unwrap();
        let body = &snippet[..close];
        let commas = body.matches(',').count();
        assert!(
            commas >= 3,
            "sunDir must carry 4 elements (≥ 3 commas); got body:\n{body}"
        );
    }

    #[test]
    fn description_with_quotes_and_newlines_escapes() {
        let mut p = Project::new("escape", 4);
        let mut info: MapInfo = (&p).into();
        info.description = Some("has \"quotes\" and\nnewlines".to_string());
        let s = render_mapinfo(&info);
        assert!(
            s.contains(r#"description = "has \"quotes\" and\nnewlines""#),
            "got:\n{s}"
        );
        let _ = &mut p; // silence unused
    }

    #[test]
    fn authored_start_positions_replace_default_pair() {
        let mut p = Project::new("teams", 8);
        p.start_positions = vec![
            StartPosition {
                team_id: 0,
                x_elmo: 500,
                z_elmo: 600,
            },
            StartPosition {
                team_id: 1,
                x_elmo: 1500,
                z_elmo: 1600,
            },
            StartPosition {
                team_id: 2,
                x_elmo: 2500,
                z_elmo: 2600,
            },
        ];
        let s = render(&p);
        // 25/75 default must not appear.
        assert!(!s.contains("x = 1024,\n        z = 1024,"), "got:\n{s}");
        // Authored coords land in teams[].
        assert!(s.contains("x = 500,"), "got:\n{s}");
        assert!(s.contains("z = 600,"), "got:\n{s}");
        assert!(s.contains("x = 1500,"), "got:\n{s}");
        assert!(s.contains("z = 1600,"), "got:\n{s}");
        assert!(s.contains("x = 2500,"), "got:\n{s}");
        assert!(s.contains("z = 2600,"), "got:\n{s}");
        // All three [0], [1], [2] indices must appear.
        assert!(s.contains("[0] = {"));
        assert!(s.contains("[1] = {"));
        assert!(s.contains("[2] = {"));
    }

    #[test]
    fn teams_indices_are_dense_and_ordered() {
        // teams[] is positional in the flat pool — index reflects
        // emission order, NOT the project's team_id.
        let mut p = Project::new("ordered", 4);
        p.start_positions = vec![
            StartPosition {
                team_id: 3,
                x_elmo: 100,
                z_elmo: 100,
            },
            StartPosition {
                team_id: 0,
                x_elmo: 200,
                z_elmo: 200,
            },
            StartPosition {
                team_id: 1,
                x_elmo: 300,
                z_elmo: 300,
            },
        ];
        let s = render(&p);
        // C1's `From<&Project> for MapInfo` sorts by team_id, so the
        // emission order is the team_id-sorted view: 0, 1, 3 → x =
        // 200, 300, 100.
        let p0 = s.find("[0] = {").unwrap();
        let p1 = s.find("[1] = {").unwrap();
        let p2 = s.find("[2] = {").unwrap();
        assert!(p0 < p1 && p1 < p2);
        let block0 = &s[p0..p1];
        let block1 = &s[p1..p2];
        let block2 = &s[p2..];
        assert!(block0.contains("x = 200,"));
        assert!(block1.contains("x = 300,"));
        assert!(block2.contains("x = 100,"));
    }

    #[test]
    fn smt_filename_always_matches_project_name() {
        let p = Project::new("smoke", 2);
        let s = render(&p);
        assert!(
            s.contains(r#"smtFileName0 = "maps/smoke.smt""#),
            "got:\n{s}"
        );
        assert!(s.contains(r#"mapfile = "maps/smoke.smf""#), "got:\n{s}");
    }

    #[test]
    fn determinism_repeated_render_byte_identical() {
        // NFR-Determinism: render twice, expect byte-identical output.
        let mut p = Project::new("det", 4);
        p.min_height = -10.0;
        p.max_height = 200.0;
        p.start_positions = vec![
            StartPosition {
                team_id: 0,
                x_elmo: 100,
                z_elmo: 100,
            },
            StartPosition {
                team_id: 1,
                x_elmo: 900,
                z_elmo: 900,
            },
        ];
        let a = render(&p);
        let b = render(&p);
        assert_eq!(a, b);
    }

    #[test]
    fn modtype_is_three_for_chobby_visibility() {
        let p = Project::new("chobby", 4);
        let s = render(&p);
        assert!(s.contains("modtype = 3,"), "got:\n{s}");
    }

    #[test]
    fn depend_contains_map_helper_v1() {
        let p = Project::new("dep", 4);
        let s = render(&p);
        assert!(s.contains(r#""Map Helper v1""#), "got:\n{s}");
    }

    #[test]
    fn extractor_radius_is_bar_eighty() {
        // PITFALL: engine default 500 breaks mex snap; BAR uses 80.
        let p = Project::new("mex", 4);
        let s = render(&p);
        assert!(s.contains("extractorRadius = 80.0"), "got:\n{s}");
    }

    #[test]
    fn atmosphere_fog_start_and_end_differ() {
        // PITFALL: fogStart == fogEnd breaks build-ETA renderer.
        let p = Project::new("fog", 4);
        let s = render(&p);
        assert!(s.contains("fogStart = 0.1"), "got:\n{s}");
        assert!(s.contains("fogEnd = 1.0"), "got:\n{s}");
    }

    #[test]
    fn keys_sorted_alphabetically_top_level() {
        // Determinism + diff-friendliness: scan known top-level keys
        // and assert their positions are in alphabetic order.
        let p = Project::new("sort", 4);
        let s = render(&p);
        let mut last_pos = 0usize;
        for key in [
            "atmosphere",
            "depend",
            "extractorRadius",
            "lighting",
            "mapfile",
            "maphardness",
            "modtype",
            "name",
            "smf",
            "version",
        ] {
            let needle = format!("\n  {} =", key);
            let pos = s.find(&needle).unwrap_or_else(|| {
                panic!("top-level key '{key}' missing in:\n{s}");
            });
            assert!(
                pos > last_pos,
                "key '{key}' out of order at pos {pos} (last {last_pos});\n{s}"
            );
            last_pos = pos;
        }
    }

    #[test]
    fn splats_arrays_render_as_seq() {
        let p = Project::new("splats", 4);
        let s = render(&p);
        // texScales = [0.02; 4]; texMults = [1.0; 4].
        assert!(s.contains("texScales = {"));
        assert!(s.contains("texMults = {"));
        // Each array contains four 0.02 / 1.0 entries.
        let tex_scales_chunk = {
            let start = s.find("texScales = {").unwrap();
            let end_rel = s[start..].find('}').unwrap();
            &s[start..start + end_rel + 1]
        };
        assert_eq!(
            tex_scales_chunk.matches("0.02,").count(),
            4,
            "splats.texScales should have four 0.02 entries; got:\n{tex_scales_chunk}"
        );
    }

    #[test]
    fn terrain_types_zero_emits_default_entry() {
        let p = Project::new("terrain", 4);
        let s = render(&p);
        assert!(s.contains("terrainTypes = {"), "got:\n{s}");
        assert!(s.contains("[0] = {"), "got:\n{s}");
        assert!(s.contains(r#"name = "Default""#), "got:\n{s}");
    }

    #[test]
    fn output_terminates_with_return_mapinfo() {
        let p = Project::new("ret", 4);
        let s = render(&p);
        assert!(
            s.ends_with("return mapinfo\n"),
            "tail:\n{}",
            &s[s.len() - 80..]
        );
    }
}
