//! `mapconfig/map_metal_layout.lua` emitter (ADR-029).
//!
//! BAR's `map_metal_spot_placer.lua` (raaar 2017, `luarules/gadgets/`)
//! reads this file at game frame 0 and paints `Spring.SetMetalAmount`
//! cells around each `{x, z, metal}` spot — the gadget iterates
//! `for i = 1, #spots do local spot = spots[i] ... end`, so the table
//! must carry contiguous integer keys 1..N (or array-style entries —
//! they're equivalent under Lua's `#` operator).
//!
//! ## Schema (BAR, verified against FINDINGS §5)
//!
//! ```lua
//! return {
//!   spots = {
//!     [1] = { x = 1024, z = 2048, metal = 2.0 },
//!     [2] = { x = 5120, z = 2048, metal = 2.0 },
//!   },
//! }
//! ```
//!
//! - `x`, `z` in **elmos** (NOT metalmap pixels). `Project.metal_spots`
//!   stores elmos throughout.
//! - `metal` is BAR's convention scalar — `2.0` standard mex, `4.0`
//!   strong central mex. Engine multiplies by `0.43 × 9 / 21 × 255` at
//!   spawn time (`map_metal_spot_placer.lua` lines 53–82).
//! - The 5×5-cross stamp pattern (21 cells) places identical density
//!   at every cell.
//!
//! ## Displayed F4 income depends on `mapinfo.maxMetal`
//!
//! BAR's `gui_metalspots.lua` widget (paints the rotating circles +
//! numeric label per spot) computes displayed income as roughly
//! `spot.worth * incomeMultiplier / 1000`. `spot.worth` aggregates the
//! per-cell `Spring.GetGroundInfo` ground-metal value across the spot
//! cluster, and that value scales linearly with `mapinfo.maxMetal`.
//! Setting `maxMetal` too low scales every spot's displayed value
//! linearly down: the editor's pre-2026-05-19 default of `0.02` made
//! every `metal=2.0` spot read as `~0.1` m/s in F4 (50× too low).
//! PITFALL §22 documents the new `1.0` default and the BAR-map median
//! range (`0.93..=4.11`).
//!
//! ## Y-coordinate is intentionally absent
//!
//! `spot` has only `x`, `z`, `metal` — no `y`. The BAR
//! `map_metal_spot_placer.lua` gadget paints a 2D metal-map cell
//! pattern; the extractor unit snap-builds at
//! `Spring.GetGroundHeight(x, z)` at construction time. Sculpting the
//! heightmap after authoring metal spots does NOT desync them — the
//! build height is sampled every spawn. (Same y-snap rule applies to
//! geo vents through `FP_featureplacer.lua`'s
//! `Spring.GetGroundHeight(x, z) + 5` — see `featureplacer.rs`.)
//!
//! ## Symmetry expansion
//!
//! The build path expands `Project.metal_spots` through the active
//! `SymmetryAxis` BEFORE handing the project to this emitter (see
//! `App::snapshot_project_for_build`). The emitter therefore walks
//! the populated source vector verbatim — mirrors are already
//! materialised by the time we run.
//!
//! ## What's NOT here — `geos` table
//!
//! Pre-2026-05-18 research stated `map_metal_layout.lua` carried a
//! sibling `geos = {...}` array. Direct read of the BAR gadget
//! (FINDINGS §5 + PITFALL §14) shows that's a **Zero-K convention,
//! not BAR**. BAR's `api_resource_spot_finder.GetSpotsGeo()` scans
//! `Spring.GetAllFeatures()` for `FeatureDef.geoThermal = true` —
//! the `geos` field in this file does nothing. Emitting it would
//! be dead weight; we instead emit `geovent` features into
//! `mapconfig/featureplacer/features.lua` (see `featureplacer.rs`,
//! C5 / Sprint 11).

use barme_core::{MetalSpot, Project};

use crate::lua_ast::{LuaKey, LuaValue, serialize};

/// Render the canonical `return { spots = {…} }` text. When
/// `Project.metal_spots` is empty, emits `spots = {}` (the gadget
/// no-ops on an empty list).
pub fn render(project: &Project) -> String {
    let spots = spots_table(project);
    let table = vec![(LuaKey::str("spots"), spots)];
    let body = serialize(&LuaValue::Table(table));
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         return {body}\n"
    )
}

/// Build the spots sub-table. Walks `Project.metal_spots` in stored
/// order (mirrors are already in this vec by the time the build path
/// invokes us), emitting `[1] = { x, z, metal }` … `[N] = { … }` for
/// diff-friendly numeric keys.
fn spots_table(project: &Project) -> LuaValue {
    if project.metal_spots.is_empty() {
        return LuaValue::Table(Vec::new());
    }
    let mut entries: Vec<(LuaKey, LuaValue)> = Vec::with_capacity(project.metal_spots.len());
    for (i, spot) in project.metal_spots.iter().enumerate() {
        entries.push((LuaKey::int((i + 1) as i64), spot_entry(spot)));
    }
    LuaValue::Table(entries)
}

/// One spot's keyed table. Keys sorted alphabetically by the AST
/// renderer's `sort_table_by_key` would re-shuffle to (metal, x, z);
/// we build them already-sorted by alpha so the output is stable
/// without an extra sort call.
fn spot_entry(spot: &MetalSpot) -> LuaValue {
    let entries = vec![
        (LuaKey::str("metal"), LuaValue::Float(spot.metal as f64)),
        (LuaKey::str("x"), LuaValue::Int(spot.x_elmo as i64)),
        (LuaKey::str("z"), LuaValue::Int(spot.z_elmo as i64)),
    ];
    LuaValue::Table(entries)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_empty_spots_for_a_blank_project() {
        let p = Project::new("blank", 4);
        let s = render(&p);
        assert!(s.contains("spots = {}"), "got:\n{s}");
        assert!(s.starts_with("-- Auto-generated"), "header missing");
    }

    #[test]
    fn output_begins_with_return_and_lua_table() {
        let p = Project::new("ret", 4);
        let s = render(&p);
        assert!(s.contains("return {"), "got:\n{s}");
    }

    #[test]
    fn determinism_repeated_render_byte_identical() {
        let p = Project::new("det", 4);
        let a = render(&p);
        let b = render(&p);
        assert_eq!(a, b);
    }

    /// PITFALL §14 / FINDINGS §5: the `geos` array is Zero-K, NOT
    /// BAR. Emitting it would be dead weight and a regression vector
    /// — the lint pass (C8) would flag it. The emitter must NEVER
    /// write a `geos =` field.
    #[test]
    fn no_geos_field_in_output_for_blank_project() {
        let p = Project::new("nogeos", 4);
        let s = render(&p);
        assert!(
            !s.contains("geos"),
            "PITFALL §14: no `geos =` table allowed; got:\n{s}"
        );
    }

    /// Even with geo vents authored, `map_metal_layout.lua` must
    /// remain a single-key (`spots`) table — geo vents emit as
    /// features in `featureplacer.rs`, not here.
    #[test]
    fn geo_vents_dont_leak_into_metal_layout() {
        use barme_core::GeoVent;
        let mut p = Project::new("only_geos", 4);
        p.geo_vents.push(GeoVent::new(100, 200));
        p.geo_vents.push(GeoVent::new(300, 400));
        let s = render(&p);
        assert!(
            s.contains("spots = {}"),
            "spots must still be empty; got:\n{s}"
        );
        assert!(!s.contains("geos"), "no `geos` table allowed; got:\n{s}");
    }

    #[test]
    fn populated_spots_render_with_integer_keys() {
        let mut p = Project::new("two_spots", 8);
        p.metal_spots.push(MetalSpot {
            x_elmo: 1024,
            z_elmo: 2048,
            metal: 2.0,
        });
        p.metal_spots.push(MetalSpot {
            x_elmo: 5120,
            z_elmo: 2048,
            metal: 4.0,
        });
        let s = render(&p);
        // Integer-keyed form ([1] = …, [2] = …) per ADR-029 + sprint
        // prompt — diff-friendliness when entries get reordered.
        assert!(s.contains("[1] = "), "expected [1] = entry; got:\n{s}");
        assert!(s.contains("[2] = "), "expected [2] = entry; got:\n{s}");
        // x / z as integers, metal as float.
        assert!(s.contains("x = 1024"), "got:\n{s}");
        assert!(s.contains("z = 2048"), "got:\n{s}");
        assert!(s.contains("metal = 2.0"), "got:\n{s}");
        assert!(s.contains("x = 5120"), "got:\n{s}");
        assert!(s.contains("metal = 4.0"), "got:\n{s}");
    }

    /// Inner keys are alphabetised (metal, x, z) — see
    /// `spot_entry`. A stable order keeps repeat-renders byte-equal
    /// and PR diffs minimal.
    #[test]
    fn spot_entry_inner_keys_alphabetised() {
        let mut p = Project::new("alpha", 4);
        p.metal_spots.push(MetalSpot {
            x_elmo: 1,
            z_elmo: 2,
            metal: 2.0,
        });
        let s = render(&p);
        let m_pos = s.find("metal =").expect("metal field present");
        let x_pos = s.find("x =").expect("x field present");
        let z_pos = s.find("z =").expect("z field present");
        assert!(m_pos < x_pos, "metal must come before x; got:\n{s}");
        assert!(x_pos < z_pos, "x must come before z; got:\n{s}");
    }

    /// PITFALL §13 / FINDINGS §5 expectation: even with one spot,
    /// the gadget reads `mapConfig.spots`. So `spots` must be the
    /// outer key, never bare entries at the top level.
    #[test]
    fn outer_table_uses_spots_key() {
        let mut p = Project::new("outer", 4);
        p.metal_spots.push(MetalSpot::new(100, 100));
        let s = render(&p);
        assert!(
            s.contains("spots = {"),
            "expected outer `spots = {{ ...`; got:\n{s}"
        );
    }
}
