//! `mapconfig/map_metal_layout.lua` emitter (ADR-029).
//!
//! Consumed by BAR's `resource_spot_finder` gadget which exposes
//! `GG['resource_spot_finder'].metalSpotsList` and `.geoSpotsList`.
//! Every mex-related widget (snap-to-spot, F4 view, AI ruins, grass
//! clearance) reads from this gadget — *not* from the SMF metalmap
//! sample. Per the research digest (§3 / §4):
//!
//! - Coordinates are in **elmos**, not metalmap pixels.
//! - Metal spots require `x` + `z`; `metal` is optional (engine
//!   fallback default 2.0).
//! - Geo vents are a second array in the same file (`geos = …`) —
//!   they ALSO need a sibling `geovent` feature in
//!   `featureplacer/features.lua` for the steam-plume visual (C5).
//!
//! ## This sprint
//!
//! C2 ships only the file scaffolding — both arrays are empty.
//! C4 (metal spots) and C5 (geo vents) populate them when the F5 / F6
//! tools land.

use barme_core::Project;

use crate::lua_ast::{LuaKey, LuaValue, serialize, sort_table_by_key};

/// Render the canonical `return { spots = {…}, geos = {…} }` text.
/// Empty bodies are valid per the resource_spot_finder gadget contract
/// (zero spots → engine falls back to the SMF metalmap, which BAR maps
/// ship as a 1×1 black PNG so the fallback finds nothing).
pub fn render(project: &Project) -> String {
    let spots = spots_seq(project);
    let geos = geos_seq(project);
    let mut table = vec![
        (LuaKey::str("spots"), LuaValue::Seq(spots)),
        (LuaKey::str("geos"), LuaValue::Seq(geos)),
    ];
    sort_table_by_key(&mut table);
    let body = serialize(&LuaValue::Table(table));
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         return {body}\n"
    )
}

/// C4 will populate this from `Project.metal_spots`. Empty placeholder
/// this sprint.
fn spots_seq(_project: &Project) -> Vec<LuaValue> {
    Vec::new()
}

/// C5 will populate this from `Project.geo_vents`. Empty placeholder
/// this sprint.
fn geos_seq(_project: &Project) -> Vec<LuaValue> {
    Vec::new()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_empty_spots_and_geos_for_a_blank_project() {
        let p = Project::new("blank", 4);
        let s = render(&p);
        assert!(s.contains("spots = {}"), "got:\n{s}");
        assert!(s.contains("geos = {}"), "got:\n{s}");
        assert!(s.starts_with("-- Auto-generated"), "header missing");
    }

    #[test]
    fn output_begins_with_return_and_lua_table() {
        let p = Project::new("ret", 4);
        let s = render(&p);
        assert!(s.contains("return {"), "got:\n{s}");
    }

    #[test]
    fn keys_sorted_alphabetically() {
        // geos before spots when sorted alpha.
        let p = Project::new("sort", 4);
        let s = render(&p);
        let p_geos = s.find("geos =").unwrap();
        let p_spots = s.find("spots =").unwrap();
        assert!(p_geos < p_spots, "expected geos before spots; got:\n{s}");
    }

    #[test]
    fn determinism_repeated_render_byte_identical() {
        let p = Project::new("det", 4);
        let a = render(&p);
        let b = render(&p);
        assert_eq!(a, b);
    }
}
