//! `mapconfig/map_startboxes.lua` emitter (ADR-029).
//!
//! Declares **ally-team start boxes** as `[0..1]`-fraction polygons of
//! the map's extent (`{0, 0}` = top-left, `{1, 1}` = bottom-right).
//! SPADS autohosts and the BAR Chobby lobby read this file to slot
//! lobby players into geographically appropriate start regions; in its
//! absence the lobby falls back to a whole-map box per ally which
//! produces terrible 8v8 matchups (PITFALL: research §7 "ranked-play
//! unfit silent failure").
//!
//! ## Shape (per research §8 / claude-research-findings.md)
//!
//! ```lua
//! return {
//!   startboxes = {
//!     [0] = { boxes = { { { 0.0, 0.0 }, { 1.0, 0.12 } } }, startpoints = {} },
//!     [1] = { boxes = { { { 0.0, 0.88 }, { 1.0, 1.0 } } },  startpoints = {} },
//!   },
//! }
//! ```
//!
//! Each `boxes` entry is a polygon — for an axis-aligned rectangle
//! the polygon is a 2-vertex `{{x0,y0}, {x1,y1}}`; for triangles or
//! arbitrary shapes (3-way FFA, etc.) it grows to N vertices.
//!
//! ## Source data
//!
//! `Project.ally_groups[i].box_polygon: Option<Vec<(f32, f32)>>`
//! (introduced by B6). Each ally group's polygon emits as one entry
//! keyed by its `id`. Groups without a polygon are skipped — leaving
//! the file empty if no group has a box (and the file overall is
//! empty if `ally_groups.len() <= 1`, since startboxes only matter for
//! ≥ 2 sides).
//!
//! ## C2 placeholder
//!
//! Until B6 lands `ally_groups`, this module emits an empty body for
//! every project. The helper `ally_group_boxes` is the seam — B6 will
//! repoint it at `project.ally_groups` and the emitter starts
//! producing real output.

use barme_core::Project;

use crate::lua_ast::{LuaKey, LuaValue, serialize, sort_table_by_key};

/// Render the canonical `return { startboxes = { … } }` text. Emits
/// an empty placeholder when the project has fewer than 2 ally groups
/// — startboxes are only meaningful for multi-side maps. Groups with
/// `box_polygon == None` are silently skipped.
pub fn render(project: &Project) -> String {
    let table = if project.ally_groups.len() <= 1 {
        // < 2 distinct sides → no useful startbox file. Emit an empty
        // `startboxes = {}` placeholder so callers that grep for the
        // file shape don't choke.
        LuaValue::Table(vec![(LuaKey::str("startboxes"), LuaValue::Table(vec![]))])
    } else {
        let mut boxes: Vec<(LuaKey, LuaValue)> = ally_group_boxes(project)
            .into_iter()
            .map(|(id, poly)| (LuaKey::int(id as i64), startbox_entry(&poly)))
            .collect();
        sort_table_by_key(&mut boxes);
        LuaValue::Table(vec![(LuaKey::str("startboxes"), LuaValue::Table(boxes))])
    };
    let body = serialize(&table);
    format!(
        "-- Auto-generated by barme-pipeline (ADR-029); do not hand-edit.\n\
         return {body}\n"
    )
}

/// Build one `[id] = { boxes = { { {x,y}, … } }, startpoints = {} }`
/// entry from a polygon. Polygons are stored as 0..1 fractions of the
/// map extent.
fn startbox_entry(polygon: &[(f32, f32)]) -> LuaValue {
    let vertices: Vec<LuaValue> = polygon
        .iter()
        .map(|&(x, y)| LuaValue::Seq(vec![LuaValue::Float(x as f64), LuaValue::Float(y as f64)]))
        .collect();
    let boxes = LuaValue::Seq(vec![LuaValue::Seq(vertices)]);
    let startpoints = LuaValue::Seq(Vec::new());
    let mut t = vec![
        (LuaKey::str("boxes"), boxes),
        (LuaKey::str("startpoints"), startpoints),
    ];
    sort_table_by_key(&mut t);
    LuaValue::Table(t)
}

/// Walk the project's ally groups and yield `(id, polygon)` pairs for
/// every group with a `box_polygon` set. Groups in id-sorted order so
/// the emitted file is byte-identical across runs (NFR-Det).
fn ally_group_boxes(project: &Project) -> Vec<(u8, Vec<(f32, f32)>)> {
    let mut out: Vec<(u8, Vec<(f32, f32)>)> = project
        .ally_groups
        .iter()
        .filter_map(|g| g.box_polygon.as_ref().map(|p| (g.id, p.clone())))
        .collect();
    out.sort_by_key(|(id, _)| *id);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_when_under_two_ally_groups() {
        let p = Project::new("solo", 4);
        let s = render(&p);
        assert!(s.contains("startboxes = {}"), "got:\n{s}");
        assert!(s.starts_with("-- Auto-generated"), "header missing");
    }

    #[test]
    fn output_uses_return_table_shape() {
        let p = Project::new("ret", 4);
        let s = render(&p);
        assert!(s.contains("return {"), "got:\n{s}");
        assert!(s.contains("startboxes ="), "got:\n{s}");
    }

    #[test]
    fn startbox_entry_renders_polygon_as_two_or_more_vertex_pairs() {
        let poly = vec![(0.0, 0.0), (1.0, 0.12)];
        let v = startbox_entry(&poly);
        let s = serialize(&v);
        assert!(s.contains("boxes ="), "got:\n{s}");
        assert!(s.contains("startpoints = {}"), "got:\n{s}");
        assert!(s.contains("0.0,"), "got:\n{s}");
        assert!(s.contains("0.12,"), "got:\n{s}");
    }

    #[test]
    fn startbox_polygon_layout_matches_research_8v8_example() {
        // Per research §8: ally 0 = top strip, ally 1 = bottom strip.
        let north = vec![(0.0, 0.0), (1.0, 0.12)];
        let south = vec![(0.0, 0.88), (1.0, 1.0)];
        let v_north = startbox_entry(&north);
        let v_south = startbox_entry(&south);
        let s_n = serialize(&v_north);
        let s_s = serialize(&v_south);
        assert!(s_n.contains("0.12,"), "n:\n{s_n}");
        assert!(s_s.contains("0.88,"), "s:\n{s_s}");
    }

    #[test]
    fn determinism_repeated_render_byte_identical() {
        let p = Project::new("det", 4);
        let a = render(&p);
        let b = render(&p);
        assert_eq!(a, b);
    }

    #[test]
    fn populated_ally_groups_emit_per_id_polygon_entries() {
        use barme_core::AllyGroup;
        let mut p = Project::new("8v8", 16);
        let mut g0 = AllyGroup::new(0);
        g0.box_polygon = Some(vec![(0.0, 0.0), (1.0, 0.12)]);
        let mut g1 = AllyGroup::new(1);
        g1.box_polygon = Some(vec![(0.0, 0.88), (1.0, 1.0)]);
        p.ally_groups.push(g0);
        p.ally_groups.push(g1);
        let s = render(&p);
        // Both ally groups produce keyed entries.
        assert!(s.contains("[0] = {"), "got:\n{s}");
        assert!(s.contains("[1] = {"), "got:\n{s}");
        // Each entry includes both `boxes` and `startpoints`.
        // Use a leading-whitespace match so "startboxes =" doesn't
        // double-count `boxes =`.
        assert_eq!(s.matches("      boxes =").count(), 2, "got:\n{s}");
        assert_eq!(s.matches("startpoints = {}").count(), 2, "got:\n{s}");
        // Polygon coords appear.
        assert!(s.contains("0.12,"), "got:\n{s}");
        assert!(s.contains("0.88,"), "got:\n{s}");
    }

    #[test]
    fn groups_without_polygon_are_skipped() {
        use barme_core::AllyGroup;
        // Two ally groups → guard allows emission. Only the group
        // with `box_polygon == Some(…)` produces an `[N] = …` entry.
        let mut p = Project::new("partial", 4);
        let mut g0 = AllyGroup::new(0);
        g0.box_polygon = Some(vec![(0.0, 0.0), (1.0, 0.5)]);
        let g1 = AllyGroup::new(1); // no polygon
        p.ally_groups.push(g0);
        p.ally_groups.push(g1);
        let s = render(&p);
        assert!(s.contains("[0] = {"), "got:\n{s}");
        assert!(
            !s.contains("[1] = {"),
            "group without polygon must be skipped; got:\n{s}"
        );
    }
}
